### ISSUE TITLE
Send composing with text.

### ISSUE THREAD

**Issue by jiseruk** [legastero/stanza#102]
Is it possible to send a text with the composing chat state using stanza.io ?  

Thanks!!

**Comment by sarumjanuch** [comment]
link: function ($scope, $element, $attrs) {
            $scope.typing = false;
            $element.on('keyup', function () {
                if ($scope.typing) {
                    if ($scope.pendingPromise) {
                        $timeout.cancel($scope.pendingPromise);
                    }
                    $scope.pendingPromise = $timeout(function () {
                        $scope.typing = false;
                        xmpps.sendChatState($scope.selectedUser.xmpp_model.jid.bare, 'paused');
                        console.log('Stop Typing');
                    }, 2000);
                }
            });
            $element.on('keydown', function () {
                if (!$scope.typing) {
                    $scope.typing = true;
                    xmpps.sendChatState($scope.selectedUser.xmpp_model.jid.bare, 'composing');

                    console.log('Start Typing');
                }
            });

**Comment by legastero** [comment]
Yes: 

```js
client.sendMessage({ to: 'peer@example.com', type: 'chat', chatState: 'composing' })
```

**Comment by sarumjanuch** [comment]
Now u have full solution...

**Comment by jiseruk** [comment]
Thanks a lot for the answers!! But what about sending the text that the user is typing in the same chatState message:
 `client.sendMessage({ to: 'peer@example.com', type: 'chat', chatState: 'composing' , text: 'I am typing...'})`

Thanks again!! Maybe It´s not part of the xmpp standard, but with Strophe.js and ejabberd, it works.
