### ISSUE TITLE
StreamManagment question

### ISSUE THREAD

**Issue by sarumjanuch** [legastero/stanza#112]
Hi Lance! I have been trying to understand the basic approach on how to make session resumption with stanza.io, and i believe i may have some misunderstanding. Is stanza.io suppose to resume session if websocket connection is used, or i should use BOSH for this to work? BTW i am using prosody as server with mod_smacks. I will tell you what is going on:
    When i am connected and just closing my application i receive in log such thing:

Oct 19 12:29:54 c2sdc2910   info    Client disconnected: connection closed
Oct 19 12:29:54 c2sdc2910   debug   Destroying session for my-company-666@my-company.local/9badcf97-61bc-4e24-910a-79fac03e9515 (my-company-666@my-company.local)
Oct 19 12:29:54 c2sdc2910   debug   mod_smacks hibernating session for up to 200 seconds

That is how this supposed to work, but this will not help me, as all my state is already lost, and i need to start everything from the beginning(correct me if i am wrong).
But in the situation where SM is designed to work as i need (short term connection lost) it not work the way it should, i believe.  It don't hibernate my session, on client i get  disconnected event fired, and in prosody log files i receive:

Oct 19 12:36:11 mod_websocket   debug   Websocket received frame: opcode=1, 26 bytes
Oct 19 12:36:11 mod_websocket   debug   Websocket received frame: opcode=1, 121 bytes
Oct 19 12:36:11 mod_websocket   debug   Websocket received frame: opcode=1, 52 bytes
Oct 19 12:36:11 c2s1057a60  debug   Received[c2s]: <r xmlns='urn:xmpp:sm:3'>
Oct 19 12:36:11 my-company.local:smacks3    debug   Received ack request, acking for 28
Oct 19 12:36:11 c2s1057a60  info    Session closed by remote with error: connection-timeout
Oct 19 12:36:11 c2s1057a60  debug   c2s stream for my-company-666@my-company.local/9e8979d1-9b78-4fd5-97db-58a4ad42c7f2 closed: session closed
Oct 19 12:36:11 c2s1057a60  debug   Received /stream:stream
Oct 19 12:36:11 c2s1057a60  debug   c2s stream for my-company-666@my-company.local/9e8979d1-9b78-4fd5-97db-58a4ad42c7f2 closed: session closed
Oct 19 12:36:11 c2s1057a60  debug   Destroying session for my-company-666@my-company.local/9e8979d1-9b78-4fd5-97db-58a4ad42c7f2 (my-company-666@my-company.local)
Oct 19 12:36:11 sessionmanager  debug   All resources of my-company-666 are now offline

Is this by design, or maybe i don't understand for which purpose SM serves? Can you advice please. For testing this i just turn off network connection on client machine for 40-60 secs and then turn it on back. I just got latest code from you repository for this tests. Also may the issue be in nginx? As we are using it to proxy connections to prosody. Sorry For so many noob questions, any response will be highly appreciate. 

Best Regards.
Eugene.

**Comment by sarumjanuch** [comment]
Hi Again i moved a little bit forward in my investigation, and did find out that in case of network outage after i reconnect my ISP back, client are able to communicate with server but sending to it 
<a h='31' xmlns='urn:xmpp:sm:3'/>
<r xmlns="urn:xmpp:sm:3"/>   
<error xmlns="http://etherx.jabber.org/streams"><connection-timeout xmlns="urn:ietf:params:xml:ns:xmpp-streams"/></error> 
<close xmlns="urn:ietf:params:xml:ns:xmpp-framing"/>
And closes connection. Also i don't see any programming logic for attempts to reconnect ws connection in case if it lost in ws transport module, is it supposed to be done on WS internal level, or you just didn't implement that?

**Comment by legastero** [comment]
First thing I'd try is to completely re-install stanza.io and its dependencies and test again. There was a bug in a dependency that was fixed a few weeks ago that affected stream management.

Beyond that, here's the current state of things:

1. When proxying, be sure to update the timeouts in nginx. By default, it wants to kill inactive WebSocket connections after 60s.
2. Stream management's purpose is to smooth over short network blips (so your client should still be open with all of the necessary state still around).
3. Your connections are being killed entirely by the `enableKeepAlive()` call because the liveness checks are failing even though the connection is apparently actually alive (this was a symptom of that dependency bug, so that might be the issue here).
4. In Prosody, stream management is not usable with BOSH (it has its own similar mechanism).
5. Prosody's latest `mod_smacks` module is currently broken with WebSocket (see http://prosody.im/issues/issue/535)
6. Stanza currently leaves the reconnection logic up to the using application (so you can do back off with a countdown timer and a manual 'reconnect now!' button).

Given 4) and 5), at the moment stream management with stanza.io and Prosody+latest `mod_smacks` simply doesn't work out of the box. :cry: 

A past version of the `mod_smacks` module did work with WebSocket, but I'll have to track down the particular version.

**Comment by sarumjanuch** [comment]
1. Yes, i convenience about that, so that is not an issue.
2. True, but after reconnect of my ISP - client becomes unusable. It sends close to server, and disconnects.
3. I don't have it on, should i explicitly disable it?
4. Good, i am using sockets so cool that i don't need BOSH.
5. I seen some talks about something very similar in prosody developers muc today (i was asking about any known issues with mod_smask and ws transport). Zash is currently waiting for a response from you there.. :)

**Comment by sarumjanuch** [comment]
Sorry here, i lied about 3. I just find out that i actually i have this, will check right now.

**Comment by sarumjanuch** [comment]
removed stanza.io from node_modules, and did npm install stanza.io. Same story. So how it looks: 
last frame with connected ISP: 
```21:14:45.112 <a h='28' xmlns='urn:xmpp:sm:3'/>```
at this point i shut down my NIC and: 
```21:15:13.599 <r xmlns="urn:xmpp:sm:3"/>
21:15:28.602 <error xmlns="http://etherx.jabber.org/streams"><connection-timeout xmlns="urn:ietf:params:xml:ns:xmpp-streams"/></error>
21:15:28.602 <close xmlns="urn:ietf:params:xml:ns:xmpp-framing"/>```
This comes from the server when i turn NIC back on:
```21:15:44.950 <a h='28' xmlns='urn:xmpp:sm:3'/>
21:15:44.951 <close xmlns='urn:ietf:params:xml:ns:xmpp-framing'/>```

**Comment by sarumjanuch** [comment]
Hi again Lance, so after changes to keepalive, now the session is hibernating, and i am able to resume it, and that it's ok till this point. But, now after i resumed session, i didn't get any messages that was sent to me during my session was hibernated. I belive this may be due to the bug in prosody, which u mentioned before. In log files after reconnect i get:
```Oct 23 10:38:41 c2s1b2cee0	warn	The client says it handled 9 new stanzas, but we only sent 0 :)
Oct 23 10:38:41 c2s1b2cee0	debug	Client h: 59, our h: 50
Oct 23 10:38:41 c2s1b2cee0	debug	#queue = 0
Oct 23 10:38:41 c2s19b0ac0	debug	#queue = 0
Oct 23 10:38:41 c2s19b0ac0	debug	#queue = 0 -- after send```

Can you confirm, am i right?
