### ISSUE TITLE
Return of getVCard

### ISSUE THREAD

**Issue by leovictorsr** [legastero/stanza#113]
Hello!

In the API documentation is showed that the usage of method getVCard() in client is:

```
client.getVCard(jid, [cb])
```

but this method returns a promise. I had to use it like this:

```
this.transport.client.getVCard(jid)
        .then((response) => this._EH_DidReceiveVCard(response));
```

**Comment by denkomanceski** [comment]
you should do this.transport.client.getVCard(err, vcard).......
the second param is the vcard, also for most of the APIs here, the first one is error, the second is the data
