### ISSUE TITLE
Handle video call to a user with multiple sessions active

### ISSUE THREAD

**Issue by wmfairuz** [legastero/stanza#121]
Hi,

Since to make a call we need to use the full JID, so how we can manage this if the targeted user has multiple sessions active (let say he's online on multiple devices).

Do we just try to initiate video call to every session he has and see which one he responds?

Thanks

**Comment by stpeter** [comment]
Jingle Message Initiation solves this problem:

http://xmpp.org/extensions/xep-0353.html

**Comment by wmfairuz** [comment]
@stpeter Thanks for the response. It looks like it will solve the problem yes.

I see that this extension is not yet supported by Stanza.io. And even in Prosody (XMPP server) that I use, I don't see 0353  supported as well.

Tough luck for me :) I might need to resort to initiate video calling to every available resource for that user until both Stanza and Prosody support this extension :)

**Comment by stpeter** [comment]
XEP-0353 isn't something that your server needs to support, it just piggybacks on standard XMPP message semantics. :-)

I suspect that Jingle Message Initiation is supported somewhere in the Otalk stack so let's find out if @legastero or @fippo knows exactly where...

**Comment by fippo** [comment]
I think @xdumaine has an implementation

**Comment by xdumaine** [comment]
Ooh, yeah, I do, but unfortunately we aren't using the xmpp bits of otalk (except for jxt). I can definitely help with how I implemented it - it wasn't too difficult.

**Comment by wmfairuz** [comment]
@stpeter @fippo Thanks for the info!

@xdumaine Do you modify stanza library for this feature, or is it more higher level modification? Thanks

**Comment by itsazzad** [comment]
@xdumaine What was the implementation? May I have that?

**Comment by xdumaine** [comment]
@wmfairuz @itsazzad The solution is JMI (xep-0353) as noted above. When initiating a call, instead of sending a session-intiate, send a jmi propose, and respond from the accepting client with a JMI proceed. You just need a client implementation that follows the spec. Unfortunately we never built it into otalk directly, though that *could* be useful.
