### ISSUE TITLE
HTTP Pre-Binding to authorize on XMPP server 

### ISSUE THREAD

**Issue by ainstainer-dvor** [legastero/stanza#134]
I want to use HTTP Pre-Binding to authorize on XMPP server (ejabberd) and I can get sid/rid/jid via PHP function. Can I use sid/rid/jid for connection via stanza.io to the same session without entering password from client side (maybe something like "attach" method from strophe.js)? 

for example:
https://metajack.im/2009/12/14/fastest-xmpp-sessions-with-http-prebinding/

I hope I can solve my problem via stanza.io coz I really like this lib :)

**Comment by legastero** [comment]
You should be able to do this like so:

```js
client = XMPP.createClient({
    jid: 'user@example.com',
    rid: 23823758,
    sid: 'jruwqrjpqejoihweprjqpr',
    boshURL: 'https://example.com/http-bind', 
    transports: [ 'bosh' ]
});
```

**Comment by juliendangers** [comment]
it still implies we have to call connect, but we're already connected. An "attach like function" would make sense, wouldn't it ?

**Comment by linksilver** [comment]
it seems to work with prosody, but not with openfire:
`404 (Invalid SID value.)`
