### ISSUE TITLE
TCP transport method

### ISSUE THREAD

**Issue by JKingweb** [legastero/stanza#140]
I was planning to use stanza.io outside a browser environment, but standard XMPP over TCP is apparently not supported. Would it be possible to add this? I've been trying to review the code, but it's not obvious to me whether stanza.io avoids making assumptions which would not hold true with straight XMPP (in particular, use of default XML namespace and prefixes).

**Comment by legastero** [comment]
There's nothing preventing support for direct TCP. I just haven't done it yet.

**Comment by sarumjanuch** [comment]
Lance, i may take a look at adding new transport type and creating tcp transport based on node https://nodejs.org/api/net.html#net_new_net_socket_options, ok?
