### ISSUE TITLE
Create a plugin for browser 

### ISSUE THREAD

**Issue by rikuhen** [legastero/stanza#146]
Hi, i want create a plugin ([XEP-0096: SI File Transfer](http://xmpp.org/extensions/xep-0096.html)), how i can create one?

**Comment by thesabbir** [comment]
Use jingle file transfer

**Comment by rikuhen** [comment]
yeh, i know it but i need use XEP-0096 :(

**Comment by kamarules74** [comment]
https://xmpp.org/extensions/xep-0137.html 
just try this link .. rikuhen
