### ISSUE TITLE
Message Archive Search

### ISSUE THREAD

**Issue by denkomanceski** [legastero/stanza#151]
Hi,

I have one question regarding message archiving. Is it possible to add some custom attribute to the message stanza so I will be able to search the archive by some metadata like Slack has. 
For example I want to search this room's archive to check for all the links or for a mention or something, but this metadata I will add as a custom attribute in the stanza message, so I will query by that? Anyone has something idea how to implement this ?

Thanks

**Comment by gaurangkela** [comment]
have a look [here](https://github.com/legastero/stanza.io/issues/143) and [here](https://gist.github.com/scastillo/a91775a952b358af2ab7e5b43378631b)
