### ISSUE TITLE
MUC History messages

### ISSUE THREAD

**Issue by denkomanceski** [legastero/stanza#154]
Is fetching histroy messages from room different than from one on one chat  ?

One on one chat we are able to fetch like this:

```
client.searchHistory({
                with: user.jid,
                rsm: {max: number || 20, before: user.firstTimestamp || true},
                complete: false
})
```

how should we do for MUC ?

**Comment by uncleNight** [comment]
Using ```jid``` instead of ```with``` works for MUC history.
Just make sure you've enabled ```mam_muc``` module server-side (that's the name for Prosody).

**Comment by CricketLaChica** [comment]
Is there a way for stanza.io to use MAM_1 instead of it's default MAM_2?
