### ISSUE TITLE
TypeError: Function.caller used to retrieve strict caller occurs when calling Client.disconnect()

### ISSUE THREAD

**Issue by EricTiger1986** [legastero/stanza#157]
My app is working on IOS system. After my app enter background and re-back. App needs to disconnect WS, so app calls disconnect() function. Sometimes, the error "TypeError: Function.caller used to retrieve strict caller" will occur. This error doesn't occur in Android.

**Comment by polyn0m** [comment]
@EricTiger1986 you resolve this problem?

**Comment by EricTiger1986** [comment]
Use 'try' to avoid it.

**Comment by polyn0m** [comment]
Already use it, but in this case connection not disconnect i'm wait 1-3 seconds and try again... It's very very bad...
