### ISSUE TITLE
Add example usage of getRoomMembers() to docs/Reference.md

### ISSUE THREAD

**Issue by superp00t** [legastero/stanza#162]
I'm not sure how to get the names of all the users in a MUC using getRoomMembers. How can I do this?

**Comment by superp00t** [comment]
After consulting the stanza.io source code for a bit, I came up with this: 
`client.getRoomMembers('lobby@conference.example.com', { items: [{ role: 'participant' }] }, function (err, res) {
                for(var x in res.mucAdmin.items) {
                    console.log(res.mucAdmin.items[x].jid.bare)
                }
});`
Which outputs the JIDs of the MUC users who are using the role 'participant'.

**Comment by superp00t** [comment]
There is a problem, though: the above code only works when the client's MUC role is Moderator. If I attempt to use that code as a non-admin user, it errors with a condition: "forbidden".

**Comment by saint739** [comment]
I think need this example add to documentation. I spent more time for view code and I can`t build right query.
Bit thanks  superp00t!
