### ISSUE TITLE
Receive Message

### ISSUE THREAD

**Issue by ksarkar123** [legastero/stanza#164]
How I will receive a message form particular jid using method in stanza.io

**Comment by abador** [comment]
You can get an event when you send a message or receive it:
`client.on('message', function (data) {
        logger.info("Got message");
        var message = {
            id: data.id,
            from: data.from.bare,
            to: data.to.bare,
            body: data.body
        };
        sendDataToSocket(socket, "message", message);
    });
    client.on('message:sent', function (data) {
        logger.info("Message sent");
        var message = {
            id: data.id,
            to: data.to.bare,
            body: data.body
        };
        sendDataToSocket(socket, "message", message);
    });`

**Comment by AlexWehe** [comment]
@abador it's possible to rescue the date from the data object?
