### ISSUE TITLE
chat event not firing

### ISSUE THREAD

**Issue by paniclabde** [legastero/stanza#167]
Hi,

I successfully connected to my ejabberd server and I am able to send messages to another account which receives them in the Triliian App on my iPhone.

The only problem is, when I try to send messages back to the user logged in via stanza.io, the chat event is not firing...

I tried handling the 'stream:data' event to check if the stanzas are received and I succesfully receive them when sending the messages to the logged in user...

Has anyone any idea why the chat event is not firing?

Here is my code:

```
var client = XMPP.createClient({
    jid: '********@********',
    credentials: {
        username: '********',
        password: '********',
        host: '********',
        serviceType: 'XMPP',
        realm: '********'
    },
    transports: ['bosh'],
    boshURL: 'http://********:5280/http-bind/'
});

client.on('session:started', function () {
    console.log('session started');
    client.getRoster();
    client.sendPresence();
});

client.on('chat', function (msg) {
    alert('chat event');
    console.log(msg);
});

client.on('stream:data', function (data) {
    console.log(data);
});
```

Thanks for your help :-)

**Comment by sevnlabs** [comment]
It seems like I have additional problems... client.getRoster() runs into a timeout after 30s and it seams like searchHistory has the same problem...
I wonder if there's a bigger problem like incompatibility with ejabberd or my ejabberd configuration is messed up...
I tried using Websockets but only get "Connection refused" if I try to access it...

Sending messages works well, and I do receive presence and message stanzas... Trillian and the macOS Messages App are working fine with my ejabberd setup.
