### ISSUE TITLE
Multiple field elements while createNode - PubSub

### ISSUE THREAD

**Issue by chauriya** [legastero/stanza#168]
Using createNode method i'am able to generate below iq, which is : 
`<iq xmlns="jabber:client" type="set" to="john@example" id="ae7545c6-c6bc-4449"><pubsub xmlns="http://jabber.org/protocol/pubsub"><create node="176fbf45-b6ea-4d15"/><configure><x xmlns="jabber:x:data"/></configure></pubsub></iq>`

> client.createNode(jid, node, 'configure', function (err, resp) {
>                 console.log(resp);
>              });

Now iam looking for to have multiple fileds element inside x element like 

```
<iq type='set'
    from='hamlet@denmark.lit/elsinore'
    to='pubsub.shakespeare.lit'
    id='create2'>
    <pubsub xmlns='http://jabber.org/protocol/pubsub'>
      <create node='princely_musings'/>
      <configure>
        <x xmlns='jabber:x:data' type='submit'>
          <field var='FORM_TYPE' type='hidden'>
            <value>http://jabber.org/protocol/pubsub#node_config</value>
          </field>
          <field var='pubsub#access_model'><value>whitelist</value></field>
        </x>
      </configure>
    </pubsub>
</iq>
```

Please help me achieving this.

Thanks!!

**Comment by davidstoker** [comment]
The third parameter, `config`, in the `createNode` function in the PubSub plugin lets you define the data form values. This would create the iq you're wanting for example:

```
client.createNode('hamlet@denmark.lit', 'princely_musings', {
      'type': 'submit',
      'fields' : [{
          name: 'FORM_TYPE',
          type: 'hidden',
          value: 'http://jabber.org/protocol/pubsub#node_config'
        }, {
          name: 'pubsub#access_model',
          value: 'whitelist'
        }
      ]
    });
```

You can look at the JXT here (https://github.com/otalk/jxt-xmpp/blob/master/src/dataforms.js) to see all the data form options.
