### ISSUE TITLE
Need custom xml elements for delivery and read receipts

### ISSUE THREAD

**Issue by rashkat** [legastero/stanza#169]
Hi 
I am using different elements for getting delivery and read receipts. following are my raw messages

```
<body xmlns='http://jabber.org/protocol/httpbind' ack='324554995'><message from="xxx@yyy" to="sss@yyy" xmlns="jabber:client"><send xmlns="urn:xmpp:receipts" id="510d9bbb-87b4-4f72-ac44-786fe40a79fe"/><delay xmlns="urn:xmpp:delay" stamp="2016-07-06T14:10:37.740Z"/></message></body>

<body xmlns='http://jabber.org/protocol/httpbind' ack='324554995'><message from="xxx@yyy" to="sss@yyy" xmlns="jabber:client"><delivered xmlns="urn:xmpp:receipts" id="510d9bbb-87b4-4f72-ac44-786fe40a79fe"/><delay xmlns="urn:xmpp:delay" stamp="2016-07-06T14:10:37.740Z"/></message></body>

<body xmlns='http://jabber.org/protocol/httpbind' ack='324554995'><message from="xxx@yyy" to="sss@yyy" xmlns="jabber:client"><read xmlns="urn:xmpp:receipts" id="510d9bbb-87b4-4f72-ac44-786fe40a79fe"/><delay xmlns="urn:xmpp:delay" stamp="2016-07-06T14:10:37.740Z"/></message></body>
```

I am not sure how can I intercept read and delivered messages as if I pass requestreceipt true I get them with event client.on('receipt', function (msg)  without this specific data "send", "read" or "delivered"

one way is to add  

receipt: Utils.subAttribute(_xmppConstants.Namespace.RECEIPTS, 'received', 'id'),
receipttype: Utils.subAttribute(_xmppConstants.Namespace.RECEIPTS, 'receipttype', 'not sure?'),

in JXT definition for message element and parse it in toJSON (which is recursive function and I find it  difficult to understand and change. Is there any easy way to handle this?

Thanks in advance
RKat

**Comment by rashkat** [comment]
@legastero Any help in this regard would be much appreciated. Apologies if the question does not make sense I am pretty beginner in xmpp world.

**Comment by jlibrun22** [comment]
I know this is old, but I think doing it this way is unneccessary... and you can just use stanza's build in read receipt code.

   ```
  client.sendMessage({
                id: id,
                to: to,
                body: body,
                requestReceipt: true,
                type: 'chat'
            });
```

then when you receive a message you can do something like 

```
 client.on('message', (msg) => {
        if(msg.hasOwnProperty('receipt')){
            //Handle message read
        }
    });

```
As for your other issue, distinguishing between delivered and read... I had that same exact problem so I made a PR to the repo so that you can control sending read receipts.

```
XMPP.createClient({
                      jid: jId,
                      password: xmppPassword,
                      wsURL: socketUrl,
                      transports: ['websocket'],
                      sendReceipts: false
                    });
```
sendReciepts defaults to true currently. Then to send a receipt and therefore say that a message is "read" and not just delivered you can send read reciepts manually like this

```
 client.sendMessage({
                from: jId,
                to: whoever,
                receipt: messageId,
                id: client.nextId(),
            });
```
