### ISSUE TITLE
Manually inject xml messages

### ISSUE THREAD

**Issue by axelson** [legastero/stanza#172]
Is it possible to manually inject xml messages into stanza.io so that they get parsed by the xml engine and plugins?

I've tried `client.emit('raw:incoming', raw_xml_string)` but it isn't picked up by `lib/transports/websocket.js`

**Comment by axelson** [comment]
FYI, I got this working (albeit a little hacky) with this:
```
var client = XMPP.createClient()
client.on('groupchat', function(eventType, data) { 
  console.log('parsed message!', data)
}
var stanzaObj = client.stanzas.parse(xml)
client.emit('stream:data', stanzaObj)
```

**Comment by axelson** [comment]
Would be nice if there was an actual API for this so that I wouldn't need to call `client.stanzas.parse(xml)`

**Comment by dynamicdirection** [comment]
@axelson , I tried to follow your footsteps, client.stanzas.parse() always returns 'undefined'.
I provided the following XML
&lt;iq from=&apos;crone1@shakespeare.lit/desktop&apos;
    id=&apos;create1&apos;
    to=&apos;coven@chat.shakespeare.lit&apos;
    type=&apos;set&apos;&gt;
  &lt;query xmlns=&apos;http://jabber.org/protocol/muc#owner&apos;&gt;
    &lt;x xmlns=&apos;jabber:x:data&apos; type=&apos;submit&apos;/&gt;
  &lt;/query&gt;
&lt;/iq&gt;

please help,
Natan

**Comment by dynamicdirection** [comment]
The red X should looks like jabber:x:data   JABBER  then COLON then X then COLON then DATA
