### ISSUE TITLE
Running in node with normal sockets?

### ISSUE THREAD

**Issue by silverbucket** [legastero/stanza#185]
Hello, I'm a bit confused as to the capabilities of `stanza.io`. Does this function as a client + server? Or does it talk directly to other XMPP services? In which case I'm unsure of why you only support BOSH or WebSockets and not direct TCP?

I'd like to use the library to interface with XMPP from a node environment. Think console-based chat client. Is this possible?

**Comment by silverbucket** [comment]
ping @legastero ?

**Comment by sarumjanuch** [comment]
stanza.io don't support tcp\tls yet.
