### ISSUE TITLE
Can't connect to ejabberd via BOSH

### ISSUE THREAD

**Issue by gudvinr** [legastero/stanza#186]
Ejabberd version: both 14.04 and 16.09.
Anonymous login doesn't work. Can't connect as registered user either.

Works fine with Prosody.
Connecting via websockets to prosody and ejabberd also works.

[Pastebin link](http://pastebin.com/GxuwL2kg) with stream dump from demo.html

**Comment by juliendangers** [comment]
same problem. I noticed that a long poll request is sent before restart request (post authentication). I'll have a closer look at it tomorrow

**Comment by juliendangers** [comment]
From [XEP](http://xmpp.org/extensions/xep-0206.html)
> Upon receiving the <success/> element, the client MUST then ask the connection manager to restart the stream by sending a "restart request"
That is not respected with the current implementation.

**Comment by devdoshicengage** [comment]
@legastero I'm using the latest versions of homebrew ejabberd and npm stanza.io. If I start a bosh connection and it doesn't return any stream:features, it hangs. Is this the expected behavior?

**Comment by WilliamD0yle** [comment]
Also have the issue `it doesn't return any stream:features, it hangs`.
