### ISSUE TITLE
Suggestions and help on Improving stanza.io

### ISSUE THREAD

**Issue by thesabbir** [legastero/stanza#192]
I'll be happy to contribue with following things:

* Rewriting codebase with ES6
* Integrate babel
* Integrate ESLint
* Adding FlowType
* Writing more tests cases
* JSDoc and generated documentation website
* Improving examples and adding more
* Reducing package size

Let me if you are open to any of this. Thanks!

**Comment by abador** [comment]
I can help with the documentation if you want.

**Comment by Jun711** [comment]
The documentation of the api may need some work.
