### ISSUE TITLE
Help in creating stanzaio.bundle.js

### ISSUE THREAD

**Issue by ken8891** [legastero/stanza#193]
Hi,

I am using Windows and I am trying to build stanzaio.bundle.js. Please correct me if my steps are wrong. The server I am using are Openfire v4.1.0

1. mkdir Install
2. cd Install
3. git clone https://github.com/legastero/stanza.io.git
4. cd stanza.io
5. npm install
6. As I am using Windows, i have edited package.json scripts "build : make build" to  "build : browserify index.js > stanzaio.bundle.js"
7. npm run build
8. stanzaio.bundle.js is generated
9. When i try to run demo.html, I have enter
      JID: username@domain
     Password: xxx
     Websocket/Bosh Url: http://domain:7070/http-bind/ 
10. The console in the browser show this error:
          Uncaught ReferenceError: XMPP is not defined at HTMLFormElement.loginInfo.onsubmit       (demo.html:139)

What should I do to established the connection correctly? And if I do established correctly, what will I see in the browser? In the steps provided, there is this step:

6. Use the JS console to play with the XMPP client (var client).

How should I go with this step? 
Thanks for the guidance.

Regards
Kenneth

**Comment by fippo** [comment]
try
```browserify --full-paths --standalone XMPP index.js > stanzaio.bundle.js```
in step 6 (as its done in the Makefile)

**Comment by ken8891** [comment]
Hi, 

Thanks for the quick response. After i generate the bundle again, there is no error in the console. However it seems not able to connect. I received this in my browser:

**raw:outgoing**

<body xmlns="http://jabber.org/protocol/httpbind" xmlns:xmpp="urn:xmpp:xbosh" xmpp:version="1.0" to="censored" xml:lang="en" wait="30" ver="1.6" hold="1" rid="3691520758"/>

streamFeatures

{
  "sasl": {
    "mechanisms": [
      "PLAIN",
      "SCRAM-SHA-1",
      "EXTERNAL",
      "CRAM-MD5",
      "DIGEST-MD5"
    ]
  },
  "bind": {
    "jid": ""
  },
  "session": {
    "optional": true
  },
  "lang": "en"
}

**stream:data**

{
  "sasl": {
    "mechanisms": [
      "PLAIN",
      "SCRAM-SHA-1",
      "EXTERNAL",
      "CRAM-MD5",
      "DIGEST-MD5"
    ]
  },
  "bind": {
    "jid": ""
  },
  "session": {
    "optional": true
  },
  "lang": "en"
}

**raw:incoming**

<body xmlns="http://jabber.org/protocol/httpbind" xmlns:stream="http://etherx.jabber.org/streams" from="censored" authid="9o7qerq4e3" sid="9o7qerq4e3" secure="true" requests="2" inactivity="30" polling="5" wait="30" hold="1" ack="3691520758" maxpause="300" ver="1.6"><stream:features><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>EXTERNAL</mechanism><mechanism>CRAM-MD5</mechanism><mechanism>DIGEST-MD5</mechanism></mechanisms><register xmlns="http://jabber.org/features/iq-register"/><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"><optional/></session></stream:features></body>

**raw:outgoing**

<body xmlns="http://jabber.org/protocol/httpbind" xmlns:xmpp="urn:xmpp:xbosh" rid="3691520759" sid="9o7qerq4e3"><auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="EXTERNAL"></auth></body>

**raw:outgoing**

<body xmlns="http://jabber.org/protocol/httpbind" xmlns:xmpp="urn:xmpp:xbosh" rid="3691520760" sid="9o7qerq4e3"/>

**raw:incoming**

<body xmlns="http://jabber.org/protocol/httpbind" ack="3691520760"/>

**auth:failed**


**stream:error**

{
  "condition": "policy-violation",
  "text": "Failed to negotiate stream features: authentication failed"
}

**raw:outgoing**

<body xmlns="http://jabber.org/protocol/httpbind" xmlns:xmpp="urn:xmpp:xbosh" type="terminate" rid="3691520761" sid="9o7qerq4e3"/>

**sasl:failure**

{
  "lang": "en",
  "condition": "not-authorized"
}

**stream:data**

{
  "lang": "en",
  "condition": "not-authorized"
}

**raw:incoming**

<body xmlns='http://jabber.org/protocol/httpbind' ack='3691520760'><failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><not-authorized/></failure></body>

**bosh:terminate**

{
  "ack": 3691520761,
  "from": "",
  "to": "",
  "type": "terminate",
  "version": "1.0"
}

**stream:end**


**disconnected**

Client instance: {
  "rid": 3691520757,
  "wait": 30,
  "maxRetries": 5,
  "useStreamManagement": true,
  "transports": [
    "bosh"
  ],
  "sasl": [
    "external",
    "scram-sha-1",
    "digest-md5",
    "plain",
    "anonymous"
  ],
  "jid": "username@domain",
  "boshURL": "http://domain:7070/http-bind/ ",
  "server": "domain name",
  "credentials": {
    "password": "xxx"
  }
}

**raw:incoming**

<body xmlns="http://jabber.org/protocol/httpbind" type="terminate" ack="3691520761"/>

Any idea where went wrong?

Best Regards
Kenneth

**Comment by nitinmukesh** [comment]
I am facing the same problem.

**Comment by vitalyster** [comment]
Your client and server are negotiate SASL EXTERNAL authentication mechanism (which mean you need to provide client certificate issued to your xmpp address) but authentication was failed (you didn't provide any certificate, right?). Just disable EXTERNAL mechanism for now in server and/or client (and I think it should not be enabled by default)

**Comment by earayo** [comment]
@ken8891 I built in the following way: https://github.com/earayo/stanza.io-demo
I hope it can help you.
