### ISSUE TITLE
react-native support, documentation?

### ISSUE THREAD

**Issue by MattFoley** [legastero/stanza#197]
I've seen a few different places pointing to this repository as a good start for a React Native XMPP implementation. Has anyone tried this, is there documentation available on how to link this repository with React Native?

**Comment by MattFoley** [comment]
From what I can tell, and based on this PR, the biggest change required is to add a new "transport" class which implements all of the existing methods in "websocket.js". https://github.com/legastero/stanza.io/pull/180

**Comment by MattFoley** [comment]
Here's how far I've gotten so far! 
https://github.com/MattFoley/react-native-stanza-demo

**Comment by MattFoley** [comment]
I was able to get this running in RN 0.40, will update the example later.

**Comment by MattFoley** [comment]
I updated the example project, it's fully working to send 1 to 1 messages through a local ejabberd instance to user connected to the local ejabberd instance via Spark.

**Comment by MattFoley** [comment]
@legastero Now that I have this running with React Native, would you have some preference of how to add this to your documentation? Perhaps as a wiki article?

**Comment by trevorwhealy** [comment]
@MattFoley I wasn't able to run your Android example using Bosh, but the iOS counterpart with Bosh was working fine.

**Comment by MattFoley** [comment]
I haven't been using Bosh, FYI. Just "wss://".

**Comment by aspidvip** [comment]
how install to react native? please?

**Comment by aspidvip** [comment]
`Unable to resolve module ctypto from .....`

**Comment by aspidvip** [comment]
install crypto => not work!

**Comment by shubham1164** [comment]
Have u found any way to use this in react native?

**Comment by legastero** [comment]
https://github.com/legastero/stanza/blob/master/docs/React_Native.md
