### ISSUE TITLE
unable to build stanzaio.bundle.js using make

### ISSUE THREAD

**Issue by nitinmukesh** [legastero/stanza#201]
I am facing problem in creating build for stanza.io.

node -v
v6.9.5

npm -v
3.10.10

python
Python 2.7.13

I downloaded the source from
https://github.com/legastero/stanza.io

executed the following commands
npm install
make

I am getting error in make command, please advice what is wrong

**(node:7384) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): undefined
make × ERR  not found: make-$(MAIN)**

    

> F:\stanza.io-master>make
>     make i info Invoking all target
>     make i info Invoking test target
>     make i info Invoking lint target
>     
>       Connect using WebSocket
>     
>         √ Connected with WebSocket
>     
>       Connect using BOSH
>     
>         √ Connected with BOSH
>     
>       Convert Form XML to Data Form object
>     
>         √ should be equal
>         √ should be equal
>         √ should be equivalent
>         √ should be equal
>         √ should be equivalent
>         √ should be equivalent
>         √ should be equivalent
>         √ should be equivalent
>         √ should be equivalent
>         √ should be equivalent
>         √ should be equivalent
>         √ should be equivalent
>         √ should be equivalent
>         √ should be equivalent
>         √ should be equivalent
>         √ should be equivalent
>     
>       Convert Form Submission Results XML to Data Form object
>     
>         √ should be equal
>         √ should be equal
>         √ should be equivalent
>         √ should be equivalent
>         √ should be equivalent
>         √ should be equivalent
>         √ should be truthy
>         √ should be equivalent
>         √ should be equivalent
>         √ should be equivalent
>         √ should be equivalent
>     
>       Convert Form Item Results XML to Data Form object
>     
>         √ should be equal
>         √ should be equal
>         √ should be equal
>         √ should be equal
>         √ should be equivalent
>         √ should be equivalent
>     
>       Convert Form with Validation XML to Data Form object
>     
>         √ should be equal
>         √ should be equivalent
>         √ should be equivalent
>         √ should be equivalent
>         √ should be equivalent
>         √ should be equivalent
>     
>       Convert Form with Media Field XML to Data Form object
>     
>         √ should be equal
>         √ should be equivalent
>     
>       Form layout
>     
>         √ should be equivalent
>     
>       Form layout with nested sections
>     
>         √ should be equivalent
>     
>     
>       total:     45
>       passing:   45
>       duration:  3s
>     
>     
>     make i info Invoking build target
>     make i info Invoking lint target
>     make i info Invoking build/$(NAME).zip target
>     make i info Invoking build/$(NAME).bundle.js target
>     **(node:7384) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): undefined
>     make × ERR  not found: make-$(MAIN)**
>     
>       $ make <target...> [options]
>     
>       Options:
>         --help             Show this help output
>         --version          Show package version
>         --debug            Enable extended log output
>     
>       Targets:
>         all                Run target all
>         build              Run target build
>         clean              Run target clean
>         test               Run target test
>         lint               Run target lint
>         build/$(NAME).zip  Run target build/$(NAME).zip
>         build/$(NAME).bundle.js Run target build/$(NAME).bundle.js
>         build/$(NAME).bundle.min.js Run target build/$(NAME).bundle.min.js
>     
>       Templates:
>         ava                Generate ava setup (ava)
>         cli                Generate cli setup (minimist, tabtab, ge...)
>         default            Generate default setup (babel-cli, babel-plu...)
>         eslint             Generate eslint setup (eslint, eslint-confi...)
>         livereactload      Generate livereactload setup (babel-plugin-react-t...)
>         mocha              Generate mocha setup (mocha)
>         simple             Generate simple setup

**Comment by nitinmukesh** [comment]
Please could you upload the stanzaio.bundle.js file as I have spent 5 days without success and just can't start learning. The js is also not available on cdnjs. :(

**Comment by apparition47** [comment]
I have some [8.1.1 builds on another fork](https://github.com/switch168/stanza.io/tree/muclight+bin) if you need them. I have a custom plugin built into it though. Feel free to check it out.

**Comment by nitinmukesh** [comment]
Thank you Aaron. :)
Please also help in how did you build this.
