### ISSUE TITLE
documentation: add examples.

### ISSUE THREAD

**Issue by przemyslawjanpietrzak** [legastero/stanza#205]
Hello.

I noticed that some stanza methods has no examples, so i made couple of jasmine test for it.
Maybe it helps improve docs.

https://github.com/przemyslawjanpietrzak/stanza.io-examples-tests/blob/master/tests/history.js

**Comment by saint739** [comment]
Hello!

Please restore examples in Doc  and more other examples like this
https://github.com/legastero/stanza.io/issues/162 and others

**Comment by yusronhanan** [comment]
> Hello.
> 
> I noticed that some stanza methods has no examples, so i made couple of jasmine test for it.
> Maybe it helps improve docs.
> 
> https://github.com/przemyslawjanpietrzak/stanza.io-examples-tests/blob/master/tests/history.js

Thank you so much.
