### ISSUE TITLE
Request websocket url

### ISSUE THREAD

**Issue by ChristianPauly** [legastero/stanza#212]
Use case: I want to login to my messenger-App with every JID from every server. But I dont know want to type in the websocket-URL from my server, because I dont know it or whatever. How can I use the application?
Is there a way to request the websocket-URI from the server? And if not, is it possible to set a static websocket-Service which works for every xmpp-server?

**Comment by itsazzad** [comment]
@KrilleChritzelius You must have to know the websocket-URI to the server.
