### ISSUE TITLE
Undefined stanzaObj on raw:incoming event

### ISSUE THREAD

**Issue by ianngiaw** [legastero/stanza#215]
I am getting an `Uncaught TypeError: Cannot read property '_name' of undefined` that is thrown at this line https://github.com/legastero/stanza.io/blob/master/lib/transports/websocket.js#L68 because `stanzas.parse(data)` in https://github.com/legastero/stanza.io/blob/master/lib/transports/websocket.js#L58 returns undefined and doesn't throw an error.

When inspecting the event data I get this:
```xml
<iq type="get" from="<host>" to="<user>@<host>" id="tigase-ping">
  <ping xmlns="urn:xmpp:ping"/>
</iq>
```

Is there any possible way to fix this issue?

**Comment by Robophil** [comment]
@ianngiaw did you find a solution to this issue?

**Comment by andreieftimie** [comment]
I've seen this a lot. `stanza.io` throws this when it's unable to parse a xml stanza. It does not throw an error where it should be, the code goes further and it tries to access properties of `undefined`.

I'll find the code path quickly.

**Comment by andreieftimie** [comment]
This is where it fails: https://github.com/legastero/stanza.io/blob/adbf184ae1df57d7c94dd8b00eee01e04514cabf/lib/transports/websocket.js#L57-L68

Notice that we are in a try / catch. The try failed, but `stanzaObj` remains `undefined`

**Comment by Robophil** [comment]
ok. I just checked out this https://github.com/legastero/stanza.io/blob/master/lib/transports/websocket.js#L68 as referenced by @ianngiaw. I'm using https://github.com/xmppjs/xmpp.js/ as my xmpp server

**Comment by ianngiaw** [comment]
@Robophil I still haven't been able to find a solution to this issue.

**Comment by Robophil** [comment]
No problem @ianngiaw. I ended up using [this](https://www.npmjs.com/package/xmpp.js) worked fine for me.
