### ISSUE TITLE
XEP-0384 OMEMO implementation

### ISSUE THREAD

**Issue by Urbiwanus** [legastero/stanza#216]
Please think about implementing OMEMO (XEP-0384) ( https://conversations.im/omemo/ ).
@keyser-soeze did an implementation in the https://github.com/cryptocat/cryptocat project. 

File : https://github.com/cryptocat/cryptocat/blob/master/src/js/omemo.js 

Regards

**Comment by Urbiwanus** [comment]
FYI :  I added stanza.io to [https://omemo.top/](https://omemo.top/)

**Comment by legastero** [comment]
The standardization story at the XSF for OMEMO is a mess right now, so I really don't want to touch anything until that is sorted out. Otherwise, yes, I'm eager to add support.

But it is also the sort of feature that really requires deeper app-level integration that wouldn't be appropriate for a library to handle 100%. So we could provide all of the convenience methods and stanza definitions needed, but it wouldn't be able support OMEMO 'out of the box' without additional setup.

**Comment by Urbiwanus** [comment]
@legastero 
Great news 
Have you checked @keyser-soze implementation ? May it can help to get a good starting point

**Comment by trillerpfeife** [comment]
It seems that XEP-0384: OMEMO Encryption Version 0.2 (2017-06-02) will stay now with the SignalProtocol. Any further development using Olm will be a new XEP.
So eventually development on OMEMO on stanza.io could be started.

**Comment by the-eater** [comment]
I've created, (most likely) another, implementation of OMEMO for stanza.io, [here](https://github.com/the-eater/Fossil/tree/master/src/fossil/stanzaio).

If there is any intrest here I can clean it up a bit and extract it from this project.

it depends on [libsignal](https://github.com/signalapp/libsignal-protocol-javascript) and is tested against Conversations, [Dino](/dino/dino) and Gajim, the only thing that needs to be implemented on the user end, is the store which stores the keys, pretty much the same as the one needed to implement for libsignal to work.

**Comment by mmikel** [comment]
Of course it's very interesting!

**Comment by andrewvmail** [comment]
@the-eater interested here !

**Comment by the-eater** [comment]
@andrewvmail I'll try to make some time this weekend :)

**Comment by mmikel** [comment]
any news?

**Comment by goors** [comment]
any news?

**Comment by the-eater** [comment]
I don't have time (and/or motivation) to clean it up completely, but this should work: https://github.com/the-eater/stanza.io/tree/feature/omemo/lib/plugins

All API's are async, the hints plugin is needed to tell the XMPP server that the message should be stored server side

There is a lot of ES6 usage in there, but you should be able to run it through babel without problems. I've edited so far that it _should_ run in all current browsers

usage and how to implement can be found here: 

Initialization: https://github.com/the-eater/Fossil/blob/master/src/fossil.js#L62
Sending messages: https://github.com/the-eater/Fossil/blob/master/src/fossil/contact.js#L46
Storage: https://github.com/the-eater/Fossil/blob/master/src/fossil/storage.js
Decryption and decoding: https://github.com/the-eater/Fossil/blob/master/src/fossil/message.js#L19

**Comment by mmikel** [comment]
Cleanapped version ;) Tested with Chrome browser and Conversations

[omemo.zip](https://github.com/legastero/stanza.io/files/2652911/omemo.zip)

**Comment by oliverschulze** [comment]
Hi,
I have seen there is some kind of support for OMEMO within the code (xep0384.ts). Is there any information how to use this?

**Comment by Neustradamus** [comment]
Any news on it?

**Comment by IgorVNC** [comment]
Hey @mmikel, thank you for providing a zipped version, very helpful! 

May I ask you one clarification please 

```
  async getAnnouncedDeviceIds(jid) {
    if (!jid) {
      jid = this.client.jid;
    }

    if (typeof jid !== 'string') {
      jid = jid.bare;
    }

    if (!this.subscriptions.has(jid)) {
      try {
        await this.client.subscribeToNode(jid, 'eu.siacs.conversations.axolotl.devicelist');
      } catch (e) {
      }
      this.subscriptions.add(jid);
    }

   ....
```

Is it really needed to subscribe to own user node? (e.g. when 'jid' is not passed here) 

Thanks in advance

**Comment by the-eater** [comment]
@IgorVNC when announcing the device list you need to retain the old device ids, so that's why we subscribe to it see e.g.

https://github.com/the-eater/Fossil/blob/c8484d5df67374cc52c0ec0625a35e1a903c0f91/src/fossil/stanzaio/omemo.js#L354
