### ISSUE TITLE
Any interest in a Muc Subscription plugin?

### ISSUE THREAD

**Issue by MattFoley** [legastero/stanza#217]
I'm building the basics of a muc/subscribe plugin for Stanza, based on Ejabberd's requirements that are described [here](https://docs.ejabberd.im/developer/xmpp-clients-bots/proposed-extensions/muc-sub/).

This is still a proposed specification, but would there be any interest in this here?

**Comment by legastero** [comment]
I'd prefer for there to be a XEP for it, but I'd be interested. I've had to make similar, custom, things to this in the past.

**Comment by juliendangers** [comment]
@MattFoley I'd be really interested, did you manage to implement it ?

**Comment by dynamicdirection** [comment]
@MattFoley, did you get the MUC to work? I am trying to implement MUC for few days now, with no luck. Do you have any working code to share?
Please help,
Natan

**Comment by MattFoley** [comment]
MUC or MUC/SUB? They're two different things really. Both work well for me.

**Comment by dynamicdirection** [comment]
hi @MattFoley ,
I have a desktop app that implements the XMPP protocol. When I create a multi user chat room the stanza that I am getting (inside the web browser DevTool) is
<message xmlns='jabber:client'
         to='feizhi1@mhcure'
         from='13john1feizhi1feizhi2charvi101003@conference.mhcure'>
    <archived by='feizhi1@mhcure' id='1544646287076046' xmlns='urn:xmpp:mam:tmp'/>
    <stanza-id by='feizhi1@mhcure' id='1544646287076046' xmlns='urn:xmpp:sid:0'/>
    <x xmlns='http://jabber.org/protocol/muc#user'>
        <invite from='john1@mhcure/MatriX'/></x>
    <x jid='13john1feizhi1feizhi2charvi101003@conference.mhcure' xmlns='jabber:x:conference'/>
    <body xml:lang='en'>john1@mhcure/MatriX invites you to the room 13john1feizhi1feizhi2charvi101003@conference.mhcure</body>
</message>

when I am using either "client.invite" or "client.directInvite", the stanza looks different.
The first issue comes to mind is the "from" attribute on the "message" node. In this case it comes from the room. 
When I use either "invite" or "directInvite" the from is coming for the "logged in" user, not from the room.

Do I need to use  a different function? (other than invite,directInvite)
please help,
Natan

**Comment by dynamicdirection** [comment]
I posted an XML but the message broke it, here is after encoding:
&lt;message xmlns=&apos;jabber:client&apos;
         to=&apos;feizhi1@mhcure&apos;
         from=&apos;13john1feizhi1feizhi2charvi101003@conference.mhcure&apos;&gt;
    &lt;archived by=&apos;feizhi1@mhcure&apos; id=&apos;1544646287076046&apos; xmlns=&apos;urn:xmpp:mam:tmp&apos;/&gt;
    &lt;stanza-id by=&apos;feizhi1@mhcure&apos; id=&apos;1544646287076046&apos; xmlns=&apos;urn:xmpp:sid:0&apos;/&gt;
    &lt;x xmlns=&apos;http://jabber.org/protocol/muc#user&apos;&gt;
        &lt;invite from=&apos;john1@mhcure/MatriX&apos;/&gt;&lt;/x&gt;
    &lt;x jid=&apos;13john1feizhi1feizhi2charvi101003@conference.mhcure&apos; xmlns=&apos;jabber:x:conference&apos;/&gt;
    &lt;body xml:lang=&apos;en&apos;&gt;john1@mhcure/MatriX invites you to the room 13john1feizhi1feizhi2charvi101003@conference.mhcure&lt;/body&gt;
&lt;/message&gt;
