### ISSUE TITLE
How to learn about the methods used in the plugins example?

### ISSUE THREAD

**Issue by marcusegues** [legastero/stanza#220]
This piece of code, shown in part of the solution to [#47](https://github.com/legastero/stanza.io/issues/47) doesn't work any longer. What is the proper way to do it now (get access to jxt, for example?) 
```
var xmpp = require('stanza.io');
var jxt = xmpp.jxt;
var Iq = xmpp.Iq;
```
From what I understood the above code is deprecated, and now we should use plugins to create a new stanza. I saw the superfeedr example, and the doc on plugins, but I don't quite get what's going on with `withMessage` and `withDefinition`. Ultimately I want to be able to send an <iq /> stanza to get a list of online users, like [xep-0133](https://xmpp.org/extensions/xep-0133.html#get-online-users-list)?

**Comment by marcusegues** [comment]
I'm trying to send an iq of form:
```
<iq from='bard@shakespeare.lit/globe'
    id='get-online-users-list-1'
    to='shakespeare.lit'
    type='set'
    xml:lang='en'>
  <command xmlns='http://jabber.org/protocol/commands'
           action='execute'
           node='http://jabber.org/protocol/admin#get-online-users-list'/>
</iq>
```

With the code:
```
module.exports = function(client, stanzas) {
  // 1. Create and register our custom `mystanza` stanza type

  var types = stanzas.utils;

  var mystanza = stanzas.define({
    name: 'mystanza',
    element: 'command',
    namespace: 'http://jabber.org/protocol/commands',
    action: 'execute',
    node: 'http://jabber.org/protocol/admin#get-online-users-list',
  });

  stanzas.withIq(function(Iq) {
    stanzas.extend(Iq, mystanza);
  });

  // 2. Add API to the stanza.io client for sending `mystanza` data

  client.sendMyStanza = function(jid, foo) {
    client.sendIq({
      to: jid,
      type: 'set',
      mystanza,
    });
  };

  // 3. Listen for incoming `mystanza` data and emit our own event

  client.on('iq', function(iq) {
    if (iq.mystanza) {
      console.log('RECEIVED NOW ', iq);
      // client.emit('foo', iq);
    }
  });
};
```

I have a React component that contains this code in componentDidMount:
```
    const client = XMPP.createClient({
      jid: 'admin@my_server',
      password: 'password',

      // If you have a .well-known/host-meta.json file for your
      // domain, the connection transport config can be skipped.

      transport: 'websocket',
      wsURL: 'ws:my_server:5280/xmpp-websocket',
      // (or `boshURL` if using 'bosh' as the transport)
    });
    client.on('session:started', function() {
      console.log('session:started');
      client.getRoster();
      client.sendPresence();
    });

    client.on('chat', function(msg) {
      client.sendMessage({
        to: msg.from,
        body: 'You sent: ' + msg.body,
      });
    });

    client.connect();
    var plugins = require('stanza.io/lib/plugins');
    client.use(plugins);
```

And I get the following error:
`TypeError: Cannot redefine property: mystanza`

```
Uncaught TypeError: Cannot redefine property: mystanza
    at Function.defineProperty (<anonymous>)
    at JXT../node_modules/stanza.io/node_modules/jxt/index.js.JXT.add (index.js:107)
    at JXT../node_modules/stanza.io/node_modules/jxt/index.js.JXT.extend (index.js:98)
    at onlineUsers.js:15
    at JXT../node_modules/stanza.io/node_modules/jxt/index.js.JXT.withDefinition (index.js:49)
    at JXT.withIQ (shortcuts.js:72)
    at ./node_modules/stanza.io/lib/plugins/onlineUsers.js.module.exports (onlineUsers.js:14)
    at Client../node_modules/stanza.io/lib/client.js.Client.use (client.js:245)
    at ./node_modules/stanza.io/lib/plugins/index.js.module.exports (index.js:50)
    at Client../node_modules/stanza.io/lib/client.js.Client.use (client.js:245)
    at AppContainer.componentWillMount (AppContainer.js:78)
(...)
```

**Comment by marcusegues** [comment]
I changed the way I require the plugin and it works without error, though I'm still not getting the correct stanza in the end.

Instead of 
```
var plugins = require('stanza.io/lib/plugins');
client.use(plugins);
```
I'm using:
```
var myPlugin = require('stanza.io/lib/plugins/onlineUsers');
client.use(myPlugin);
```

However, the stanza that is sent out is
<iq xmlns="jabber:client" to="my_server" type="set" id="1a5d84dd-4c84-48a5-a4af-23717038b7e5"><command xmlns="http://jabber.org/protocol/commands"/></iq>

I want to have two extra attributes on that command tag: 'node' and 'action', like I see in [XEP-0133](https://xmpp.org/extensions/xep-0133.html#get-online-users-list).

**Comment by marcusegues** [comment]
The solution to building a XEP-0133 `iq` stanza as in [the XEP-0133 doc](https://xmpp.org/extensions/xep-0133.html#get-online-users-list):

```
module.exports = function(client, stanzas) {
  // 1. Create and register our custom `mystanza` stanza type
  var types = stanzas.utils;

  // types.attribute apparently defines attributes on the mystanza tag
  var mystanza = stanzas.define({
    name: 'mystanza',
    element: 'command',
    namespace: 'http://jabber.org/protocol/commands',
    fields: {
      action: types.attribute('action'),    
      node: types.attribute('node'),
    },
  });

  stanzas.withIq(function(Iq) {
    stanzas.extend(Iq, mystanza);
  });

  // 2. Add API to the stanza.io client for sending `mystanza` data

  client.sendMyStanza = function(jid, foo) {
    client.sendIq({
      to: jid,
      type: 'set',
      mystanza: {
        action: 'execute',
        node: 'http://jabber.org/protocol/admin#get-online-users-list',
      },
    });
  };

  // 3. Listen for incoming `mystanza` data and emit our own event

  client.on('iq', function(iq) {
    if (iq.mystanza) {
      console.log('Received ', iq);
    }
  });
};
```

**Comment by GregDThomas** [comment]
That's as good as far as it goes, but is there anyway to extend it such that you can have different stanza types for different commands (i.e. nodes).

For example, you want want to handle 

```
<iq from='bard@shakespeare.lit/globe' id='get-online-users-list-1' to='shakespeare.lit' type='set' xml:lang='en'>
  <command xmlns='http://jabber.org/protocol/commands'
           action='execute'
           node='http://jabber.org/protocol/admin#get-online-users-list'/>
</iq>
```
differently from 
```
<iq from='bard@shakespeare.lit/globe' id='get-active-users-1' to='shakespeare.lit' type='set' xml:lang='en'>
  <command xmlns='http://jabber.org/protocol/commands'
           action='execute'
           node='http://jabber.org/protocol/admin#get-active-users'/>
</iq>
```
Although they are both iq packets, they are conceptually very different.

**Comment by marcusegues** [comment]
@GregDThomas I believe in that case we would simply define another method on the client:
```
  client.getActiveUsers = function(jid) {
    client.sendIq({
      to: jid,
      type: 'set',
      mystanza: {
        action: 'execute',
        node: 'http://jabber.org/protocol/admin#get-active-users',
      },
    });
  };
```

**Comment by GregDThomas** [comment]
That's find for sending, but what about receiving? AFAICT, there's no in-built way to handle different IQ commands packets easily. It may be necessary to do something like ...

```
  client.on('iq', function(iq) {
    if (iq.command) {
      if (iq.command.node === 'http://jabber.org/protocol/admin#get-online-users-list') {
        console.log('Received get-online-users', iq);
      } else if (iq.command.node === 'http://jabber.org/protocol/admin#get-active-users') {
        console.log('Received get-active-users', iq);
      } else if ... {
      }
    } 
  });
```
which strikes me as a bit clunky. Is there a way to register different commands?

**Comment by marcusegues** [comment]
Even though I was able to create this very simple stanza with one `command` tag that has two custom attributes `action` and `node`, the server responds with the expected:
```
<iq from='shakespeare.lit'
    id='get-online-users-list-1'
    to='bard@shakespeare.lit/globe'
    type='result'
    xml:lang='en'>
  <command xmlns='http://jabber.org/protocol/commands'
           node='http://jabber.org/protocol/admin#get-online-users-list'
           sessionid='get-online-users-list:20040408T0337Z'
           status='executing'>
    <x xmlns='jabber:x:data' type='form'>
      <title>Requesting List of Online Users</title>
      <instructions>
          Fill out this form to request the online users
          of this service.
      </instructions>
      <field type='hidden' var='FORM_TYPE'>
        <value>http://jabber.org/protocol/admin</value>
      </field>
      <field label='Maximum number of items to show'
             type='list-single'
             var='max_items'>
        <option label='25'><value>25</value></option>
        <option label='50'><value>50</value></option>
        <option label='75'><value>75</value></option>
        <option label='100'><value>100</value></option>
        <option label='150'><value>150</value></option>
        <option label='200'><value>200</value></option>
        <option label='None'><value>none</value></option>
      </field>
    </x>
  </command>
</iq>
```

To which I should respond:
```
<iq from='bard@shakespeare.lit/globe'
    id='get-online-users-list-2'
    to='shakespeare.lit'
    type='set'
    xml:lang='en'>
  <command xmlns='http://jabber.org/protocol/commands'
           node='http://jabber.org/protocol/admin#edit-whitelist'
           sessionid='get-online-users-list:20040408T0337Z'>
    <x xmlns='jabber:x:data' type='submit'>
      <field type='hidden' var='FORM_TYPE'>
        <value>http://jabber.org/protocol/admin</value>
      </field>
      <field var='max_items'>
        <value>100</value>
      </field>
    </x>
  </command>
</iq>
```

Which means now I think I must:
- define another stanza (another custom tag) using `stanzas.define({...})`, called `x`
- `x` will have a namespace and a type, which seem to be simple properties I can specify in `stanzas.define`
- it has two `field` tags as subtags, and they have `value` tags as subtags, each with a value as a number
- I'm going to try to create these subtags by defining new tags using `stanzas.define({...})`, and extending my previously created tag using `stanzas.extend(myStanza, myNewerStanza)`. Then I can use `myNewerStanza` as a property like follows:
```
  client.sendMyStanza = function(jid, foo) {
    client.sendIq({
      to: jid,
      type: 'set',
      mystanza: {
        action: 'execute',
        node: 'http://jabber.org/protocol/admin#get-online-users-list',
        myNewerStanza: {
          attr1: ...
          attr2: ...
        }
      },
    });
  };
```
- **Not sure if this is correct or will work, but from looking at many issues and reading the available documentation and experimenting this is what I got in terms of understanding** Would really like to understand so I can write something up that is didactical about all of this.

I will probably figure this out (in a few hours), but I'd like to document exactly what's going on after I do so people who stumble upon this can save some time. Here are my current goals in understanding:
- When I use `stanzas.define({...}) it seems that I can directly define some properties on the passed in object, but only some of them (name, element, namespace) end up as attributes on the created tag (I am creating a custom tag, after all, right? Technically it's not a real stanza though, correct?). Other properties I pass in are seemingly ignored. 
- To get custom attributes on the new tag, I create a `fields` property with the value being an object. I can define a property on this object, name it as the custom property I want on my new tag, and as value I use `types.attribute('name_of_my_custom_property')`.
- I can define other properties on this `fields` object, and depending on the associated value, the property will become different things. This is not documented anywhere, so the only place to figure it out is through examples like the [superfeedr example](https://github.com/legastero/stanza.io-superfeedr/blob/master/lib/stanzas.js).
- There we see other possible values such as `types.subText(NS, 'prop_name'),`, `types.subAttribute(NS, 'http', 'code')`, and others. **It would be cool if someone could write some words on what all the possibilities are and what they're used for.**

**Comment by marcusegues** [comment]
@GregDThomas I am also doing something similar to that to handle the responses from my "get all users" stanzas.
