### ISSUE TITLE
 list of my friends 

### ISSUE THREAD

**Issue by alphapersian** [legastero/stanza#246]
how can i fetch a list of my friends , on or offline ???
can anybody send me a code snippet

**Comment by itsazzad** [comment]
This may help: https://github.com/legastero/stanza.io/blob/master/docs/Reference.md#clientsendpresenceopts

**Comment by alphapersian** [comment]
thanks a lot for reply , but the problem is that i can't get all of my friend , i send them my presence , but i can't get who they are?
i mean i may have more than 100 roster , i want to list them all even if they are offline .

**Comment by itsazzad** [comment]
AFAIK  you are sending your presence to the server and server delivers that.
In the `getRoster` you should get all from your roster.
```js
        client.on('session:started', () => {
            client.getRoster((err, result) => {
                if (err) {
                    console.error(err);
                }
                if (result) {
                    console.error(result);
                }
                client.sendPresence();
            });
        });
```
