### ISSUE TITLE
XEPs support page with version

### ISSUE THREAD

**Issue by Neustradamus** [legastero/stanza#253]
On the XEPs support page, it is possible to add version of XEPs?
https://github.com/legastero/stanza.io/blob/master/docs/Supported_XEPs.md

Examples:
- https://metronome.im/supported-xeps-list
- https://dev.gajim.org/gajim/gajim/wikis/help/GajimXEPSupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by legastero** [comment]
As requested: https://github.com/legastero/stanza/blob/master/docs/Supported_XEP_Formats.md

**Comment by Neustradamus** [comment]
Thanks a lot @legastero, good job!
Do not forget to update it when there is an update :)
