### ISSUE TITLE
Unhandled promise reject on Timeout

### ISSUE THREAD

**Issue by kinsi55** [legastero/stanza#266]
Just stumbled upon this, if I didn't have such a hard time wrapping my head around Promise chaining I'd have tried submitting a PR but I'm sure It'd be 100% "wrong".

I am using XMPP over WS and used `enableKeepAlive`. On a timeout [this](https://github.com/legastero/stanza.io/blob/master/lib/plugins/keepalive.js#L30) rejection is unhandled, apparently because `timeoutPromise` doesnt have a `.catch` for the `Promise.race`.

Am I just missing something? Thanks!

**Comment by legastero** [comment]
Which browser are you using? Or node?

The `catch()` at https://github.com/legastero/stanza.io/blob/master/lib/plugins/keepalive.js#L50 _should_ be handling this, but I'll keep poking around.

**Comment by legastero** [comment]
And you are certain that websocket is being used, yes? Otherwise I'd suspect you've also ran into https://github.com/legastero/stanza.io/issues/262

**Comment by kinsi55** [comment]
Little Update (Literally), updated to Node 8.11.2 in the meanwhile, issue still existing.
