### ISSUE TITLE
MultiUser Join in MUC

### ISSUE THREAD

**Issue by patelvanita360** [legastero/stanza#268]
Hello @legastero 

Can i join multiple user at the time of room creation ?

**Comment by dalisoft** [comment]
@patelvanite360 i think yes, the API docs is not good well written, so many users are stuck at creating, but library is great.
I too stuck here more than 1 week, but learned a lot after seen to source code, i recommend to you too =)

**Comment by dynamicdirection** [comment]
Is there a tutorial for MUC?

**Comment by saint739** [comment]
Please add example in documentation how use client.configureRoom.
