### ISSUE TITLE
Not able to start video session 

### ISSUE THREAD

**Issue by patelvanita360** [legastero/stanza#270]
Hello @sarumjanuch 

Using following demo i could not able to start Video Session, I able to transfer file using this.
http://legastero.github.io/jingle-interop-demos/stanzaio/

Getting Following error while making call
`Uncaught TypeError: Cannot read property 'id' of null

> 
http://legastero.github.io/jingle-interop-demos/stanzaio/stanzaio.bundle.js

function dumpStream(stream) {
    var info = {
        label: stream.id,
    };

`

**Comment by moeinrahimi** [comment]
I'm stuck on using the example you mentioned , i think maybe the source code is out dated
