### ISSUE TITLE
Cannot chat after 30minutes

### ISSUE THREAD

**Issue by dxtri94** [legastero/stanza#273]
Hi guys, i integrated stanza in my project.
My issue : If i leave my website after about 30-40 minutes, it cant chat anymore, cant use client,sendMessage. I think it base on session out. I set keepalive in startSession function. I wonder that it is right or wrong. It just happen in "global chat" as Multi-User Chat.
This is my startSession function and i use AngularJS
service.client.on('session:started', startSession);
// fn start session
  function startSession() {
    service.client.enableCarbons(function (err) {
      if (err) {
        console.log('Server does not support carbons');
      }
    });

//enale keep alive here
    service.client.enableKeepAlive({
      interval: 30
    });

    $timeout(function () {
      getDiscoItems();
    }, 3000);

  }
Thanks.

**Comment by xTMNTxRaphaelx** [comment]
it happen with me as well.. after a certain amount of time browser being idle, xmpp connection is stopped.
I have only added polling to re-connection, it says to me ERR_CONNECTION_REFUSED even though internet is online.

Any help why it happen and how to fix it?
