### ISSUE TITLE
How to share single instance of client object to all the respective html pages in chat app

### ISSUE THREAD

**Issue by carotkut94** [legastero/stanza#277]
I have a chat app, and stanza connects fine with the sever, now the problem is if i have a login.html file in which user will login using jid and password, and once the user logs in this page will be redirected to some chat page, where he will see all of his friends, now how can i reuse that client object that i created earlier when i logged in, instead of recreating the connection on every page.

**Comment by nitinmukesh** [comment]
Using SPA (Single page application).
