### ISSUE TITLE
How to handle a 'message not sent' status with Stream Management

### ISSUE THREAD

**Issue by DaveLomber** [legastero/stanza#287]
Hi guys, 

I'm trying to integrate a 'message sent' status via stanza.io Stream Management 

It seems we should use a 'stanza:acked' event 
https://github.com/legastero/stanza.io/blob/master/src/sm.js#L99

So we can easily understand when a message was delivered to server.

But an other thing is that we need to handle somehow a case where a message was not delivered.
But I did not found a proper way on how to handle this case

Couple questions came to my mind:
* do we need to have some timeout for the 'stanza:acked' event and if a user did not receive an acknowledgment for a message during let's sat 5 sec - then it means it's failed? 
* Is there anything integrated in stanza.io to handle this case?
* What would be a recommended way to do so?

Thanks

**Comment by DaveLombardo** [comment]
anyone has any suggestions? 
I want to found a proper flow and add it to this repo README then, so everybody will enjoy 
thanks

**Comment by piranna** [comment]
We are having the same problem. Any clue about how to know if the message was correctly received by the server?

**Comment by legastero** [comment]
https://github.com/legastero/stanza/blob/master/docs/Using_Stream_Management.md
