### ISSUE TITLE
SCRAM-SHA-1-PLUS + SCRAM-SHA-256(-PLUS) supports

### ISSUE THREAD

**Issue by Neustradamus** [legastero/stanza#295]
There is only SCRAM-SHA-1, there is not SCRAM-SHA-1-PLUS:
- https://tools.ietf.org/html/rfc5802
- https://tools.ietf.org/html/rfc6120

There is not SCRAM-SHA-256(-PLUS):
- https://tools.ietf.org/html/rfc7677
- https://tools.ietf.org/html/draft-ietf-mile-xmpp-grid

I add SCRAM-SHA-512(-PLUS): https://xmpp.org/extensions/inbox/hash-recommendations.html

**Comment by legastero** [comment]
SCRAM-SHA-256 is supported now. -PLUS is too, technically, but BOSH/WebSocket don't provide channel binding info. It'll be there once TCP/TLS support is added.

**Comment by Neustradamus** [comment]
Thanks a lot @legastero, good job!
I must to create a ticket for TCP/TLS support right now? :)
