### ISSUE TITLE
Support for Bower

### ISSUE THREAD

**Issue by ndarilek** [legastero/stanza#30]
Hello,

Looks like an interesting library. It'd be nice if I could "bower install" it, or at the very least, if a minified version was available for download. I'm under Windows, and Grunt isn't happy with my 3.4 version of Python. I understand that I could install a lower version, set up my paths, etc. but it'd be nice if I could just use Bower to fetch the minified JS as well.

Thanks! If there already is a minified distribution, feel free to point me at it for the time being.

**Comment by juanpborda** [comment]
+1

**Comment by dhcar** [comment]
+2

**Comment by kdex** [comment]
For what it's worth, it should be mentioned that `bower install otalk/stanza.io` will work, as `bower` *does* offer GitHub integration. This will essentially result in a `git clone`, and you (as maintainers) could automate some sort of building procedure over that, at least momentarily.

Other than that, I fully agree; a bower package including a production-ready build is long overdue. :)
