### ISSUE TITLE
option to Cache Stream Management ids and counters in localStorage

### ISSUE THREAD

**Issue by stefansaenger** [legastero/stanza#312]
We are using stanza.io in a hybrid angular application that also is bundled as native app using cordova.
One scenario we found is that after force-stop and restart of the app or swipe out and restart stream resumption is not possible, since all details for counters and ids are lost.

So that leads to an unpleasant case where MAM is unfortunately not sufficient.
We are using receipts and when a receipt is sent, it is not stored in MAM (with current prosody). Using mod_smacks_offline works when the app is not restarted until smacks_hibernation_time is over - in that case the receipt stanza is put to offline in prosody and delivered when the app connects again.

But when the app reconnects before smacks_hibernation_time is over, the receipt is not sent and the stanza is discarded by prosody.

One way to prevent this would be to resume the existing session, and hence we would need id and counters be chached in localStorage.

@legastero  I would love to get some feedback here - if it is positive we should be able to provide PR.

**Comment by marc0s** [comment]
We would be interested in knowing what the approach should be. As @stefansaenger says, I also think having the smacks counters saved into local/sessionStorage would be approachable.

**Comment by legastero** [comment]
The library itself _can not_ touch local/session storage; that has to be left to the using application. Node apps don't have those globals, for example.

This would need to be an event or some other callback that is fired on every change in SM state. I'm leaning toward a `client.sm.cache(stateHandler)` approach.

**Comment by legastero** [comment]
Try out the branch in https://github.com/legastero/stanza.io/pull/321 and give feedback on if that has any holes.

**Comment by marc0s** [comment]
> The library itself can not touch local/session storage; that has to be left to the using application. Node apps don't have those globals, for example.
Indeed, forgot about that.

Will try to have a look at your branch asap. Thanks!

**Comment by legastero** [comment]
https://github.com/legastero/stanza/blob/master/docs/Using_Stream_Management.md
