### ISSUE TITLE
Proper way to handle sendMessage result

### ISSUE THREAD

**Issue by ThomasChiroux** [legastero/stanza#328]
Hi,
Is there a proper way to handle sendMessage result ?
The use case is simply to add the (just now) sent message to the messages windows, but only if the message has really been sent (or perhaps at least received by the local server).

My first thought was to get and test the msg_id, like this:

```
var msg_id = client.sendMessage({
                   to: remote_jid,
                    type: 'chat',
                    body: body
                });
if (msg_id) {
   // add the message to the messages pannel here
}
```

Looking at the source, msg_id is always returned.

Using emmitted 'message:sent' event will not change anything: it's emitted even before the message is really sent:
https://github.com/legastero/stanza.io/blob/master/src/client.js#L368

I can stop verifying msg_id and always add the message in the message list, but at the cost of perhaps adding a message that is not really sent. (the other peer will think it's ok but it's not).

I'm using websocket transport, so i've looked at the transport source code: the message is not directly sent, but added to a send-queue, that's why it's certainly not trivial, but it should be possible to use the callbacks ? or better: emit the 'message:sent' event at the exact right place in the transport, just after the message is really sent ?

Or perhaps there is already a good practice that i've overlooked ?

Thanks, 
Tom.

**Comment by marcusg** [comment]
@ThomasChiroux That's a really good question, I have the same problem and hope someone can help or at least clarify _why_ this behaviour is intended.

**Comment by legastero** [comment]
https://github.com/legastero/stanza/blob/master/docs/Using_Stream_Management.md
