### ISSUE TITLE
Use `negotiationneeded` event

### ISSUE THREAD

**Issue by piranna** [legastero/stanza#350]
Make use of `negotiationneeded` on PeerConnection to be able to add streams after the `MediaSession` is stablished.

**Comment by fippo** [comment]
ONN is a bad idea and doesn't fit the model of stanza. That it has been broken until recently in Chrome is a sad example of that.

Creating a new offer when you just added a new track isn't that hard.

**Comment by piranna** [comment]
I know, but that's just what ONN does automatically, without needing to control it yourself... On my use case, I was creating the MediaSessions when ringing, and not adding the camera streams until both have accepted. Without that, I need to ask for the camera first beforehand and add it before creating the offer.
