### ISSUE TITLE
`MediaSession.addStream()` don't exist

### ISSUE THREAD

**Issue by piranna** [legastero/stanza#351]
https://github.com/legastero/stanza.io/blob/b8e20ae7f94a1b1fdf7e98071e5317f34b5969a5/test/jingle/mediasession.js#L47

In current API, `addStream` doesn't exist, being instead available `addTrack`:

https://github.com/legastero/stanza.io/blob/f2e8c000e01fdc29a56817827a84f8cc46874291/src/jingle/MediaSession.js#L180-L191

**Comment by legastero** [comment]
https://github.com/legastero/stanza/blob/master/test/jingle/mediasession.js#L48

**Comment by piranna** [comment]
Thank you :-)
