### ISSUE TITLE
Problem using addBookmarks/setBookmarks method

### ISSUE THREAD

**Issue by kai670** [legastero/stanza#354]
I'm doing this: `addBookmarks({jid: "97ac26a0-a96a-11e9-970f-0bfbb9967ff4@domain"});` but an empty list is being sent to the server.

Trying to find where the problem could be I managed to find out that `client.send(name, data)` is called with `iq` as name and the next object as `data`:

```
{
  "id": "d994e97b-c39a-4eb4-9686-02014efc7528",
  "privateStorage": {
    "bookmarks": {
      "rooms": [
        {
          "jid": "97ac26a0-a96a-11e9-970f-0bfbb9967ff4@domain"
        }
      ]
    }
  },
  "type": "set"
}
```

And that is serialized to:
```
"<iq xmlns="jabber:client" id="f9aea9ca-0981-4d37-818b-e330b622e6e4" type="set"><query xmlns="jabber:iq:private"><storage xmlns="storage:bookmarks"/></query></iq>"
```

So I suppose the problem can be in the construction of the object (not sure if it has the expected format) or in the serialization process.

I hope I provide enough information.

Thank you!

**Comment by legastero** [comment]
Fixed in 12.0.3. Thanks!!
