### ISSUE TITLE
Problem using adding "markable" element to message [XEP-0333]

### ISSUE THREAD

**Issue by kai670** [legastero/stanza#355]
I'm sending a message this way:
```
client.sendMessage({to, type, body, marker: {type: 'markable'}});
```

That creates this object:
```
{
  "to": "bob@domain",
  "type": "chat",
  "body": "z84GlCOja",
  "marker": {
    "type": "markable"
  }
}
```

That is serialized to:
```
<message xmlns="jabber:client" id="ff4e7c79-d9a6-4fd8-a67d-8c5fb66a70c4" to="bob@quobis" type="chat">
    <body>z84GlCOja</body>
</message>
```

You can see that the marker part is completely ignored.

I'm taking the marker object from [src/protocol/xep0333.ts](https://github.com/legastero/stanza/blob/master/src/protocol/xep0333.ts)

**Comment by legastero** [comment]
This should be fixed now in 12.0.7.

There were a few mapping files that weren't getting imported. I've added tests for those, and ran a script to check for any other files that weren't being imported anywhere.
