### ISSUE TITLE
Typo in xep0313.ts protocol

### ISSUE THREAD

**Issue by mathieuleddet** [legastero/stanza#357]
Hi,

I think I found a typo in **src/protocol/xep0313.ts**.

Best,
Mat

https://github.com/legastero/stanza/blob/c540b567fea10b2611ffb5353aa28deb24f72389/src/protocol/xep0313.ts#L37

I see **pagin** instead of **paging**

```typescript
export interface MAMFin {
    type: 'result';
    complete?: boolean;
    stable?: boolean;
    results?: MAMResult[];
    pagin?: Paging;
}
```

**Comment by legastero** [comment]
Yep, typo. Fix included in 12.1.0
