### ISSUE TITLE
Incorrect stanza definition for File Upload uri instead of url

### ISSUE THREAD

**Issue by mathieuleddet** [legastero/stanza#358]
Hi there,

For XEP 0363, when getting upload slots in v11 you used to parse a 'url' attribute.
Now in v12 you parse a 'uri' attribute and this is not correct.

HERE:
https://github.com/legastero/stanza/blob/109e6c90879fbaf9643010f251da6bdb61c61ce1/src/protocol/xep0363.ts#L90

and HERE:
https://github.com/legastero/stanza/blob/109e6c90879fbaf9643010f251da6bdb61c61ce1/src/protocol/xep0363.ts#L80

Should be 'url' instead of 'uri'.

Best,
Mat

XEP link for reference : https://xmpp.org/extensions/xep-0363.html

**Comment by legastero** [comment]
Thanks! Fixed in 12.1.1, along with another small 363 fix I found while making test cases.
