### ISSUE TITLE
Stream Management: checking !ack.handled

### ISSUE THREAD

**Issue by mathieuleddet** [legastero/stanza#359]
Hi there,

I had issue with *stanza:acked* not being been emitted -- useStreamManagement set to true.
I commented the conditional return in this file and it started to work back again.

https://github.com/legastero/stanza/blob/7fbb8a91d00e1de96764b2a0853c825556e88722/src/StreamManagement.ts#L158

Maybe this return should use (ack.handled === undefined)?

Best,
Mat

**Comment by legastero** [comment]
Excellent catch! Yes, that should check against undefined so it doesn't skip on 0.

Fix published in 12.1.4

**Comment by legastero** [comment]
Found a similar issue for resumed/failed processing. Fixed those in 12.1.5.
