### ISSUE TITLE
Decoding special characters in XML attribute

### ISSUE THREAD

**Issue by mathieuleddet** [legastero/stanza#364]
Hi there,

Somewhere in a stanza, I have a tag with an attribute of this form:
`<tag note="...&#xD;&#xA;...&#xD;&#xA;..."/>`

JXT parser is throwing me the following error: `"Prohibited entity: &#xD;"`

Normally, `&#xD;` refers to new line character in XML attributes ([https://www.w3.org/TR/xml-c14n/#Example-Chars](https://www.w3.org/TR/xml-c14n/#Example-Chars))

I guess this is where we should look into:
https://github.com/legastero/stanza/blob/f6a8600afa69356bb447b227161496cafddbdc76/src/jxt/Definitions.ts#L148-L171

Is there anything I can do to avoid this error?

Thanks for your feedback,
Mathieu

**Comment by legastero** [comment]
Updated to allow escaped carriage return in 12.1.7.

Thanks!
