### ISSUE TITLE
Some chars are not escaped in XML text nodes

### ISSUE THREAD

**Issue by mathieuleddet** [legastero/stanza#367]
Hi there,

I think there is an issue encoding XML text nodes:
https://github.com/legastero/stanza/blob/4e40332dc4eff49b855d8ee04359503fba75744c/src/jxt/Definitions.ts#L185

shouldn't it be this way? (like in escapeXML)

```typescript
return text.replace(/&|<|>|"|'/g, escapeXMLReplaceChar);
```

Best,
Mat

**Comment by legastero** [comment]
Should be fixed in 12.1.8.

Quotes don't need escaping in text nodes, but `<` does.
