### ISSUE TITLE
XEP-0012 plugin port from stanza v11 to v12

### ISSUE THREAD

**Issue by zicrox** [legastero/stanza#370]
Hi Stanza team.

We use this awesome xmpp client in our react native app and this roks!

We use a custom plugin to support the XEP-0012 because is the easiest way to know the last activity (online or not) of a contact regardless of his resources.

XEP-0012 is a little spec and this is our little plugin:

```js

// "lastActivity" request method (iq)
function getLastActivity(jid)
{
  return this.sendIq({
    to: jid,
    type: 'get',
    lastActivity: true,
  })
}


module.exports = function lastActivityStanza(client, stanzas)
{
  const types = stanzas.utils

  //# 1. Create and register our custom `lastActivityQuery` stanza type
  const lastActivityQuery = stanzas.define({
    name: 'lastActivity',
    element: 'query',
    namespace: 'jabber:iq:last',
    fields: {
      seconds: types.attribute('seconds'),
    }
  })

  stanzas.extendIQ(lastActivityQuery)

  //# 2. Add API to the `stanza` client for sending `lastActivity` data
  client.getLastActivity = getLastActivity
}

```

But with the last important change from v11 to v12 and typescript by we need some help to port it. By the moment we ported in the old js style some method that has changed like "sendIq" to "sendIQ"  and "stanzas.utils" to "JXT" but seems that "stanzas.extendIQ" has not exists anymore, I think only with this the plugin can be ported in the old js style.

Also we plan to port properly with typescript and pull quest it to include in the Stanza project.

**Comment by legastero** [comment]
Went ahead and added XEP-0012/XEP-0256 support in stanza 12.2.0.

https://github.com/legastero/stanza/commit/da73f3ab9b35785c1239c28ed7a4f0356531ff61

**Comment by zicrox** [comment]
Awesome man, I test it the XEP-0012 and works fine also I learned some ts :)

I will take a look at the XEP-0256, great job thanks!
