### ISSUE TITLE
searchHistory method doesn't allow `to` property

### ISSUE THREAD

**Issue by kai670** [legastero/stanza#371]
Using stanza@11 you can pass a 'to' attribute to `searchHistory` this way:
```
searchHistory({
  to: 'fbefca4b3eff@conference',
});
```

and that was transformed to:
```
<iq xmlns="jabber:client" id="7f4304f5-265a-4475-bc67-e54be9720eb1" to="fbefca4b3eff@conference" type="set">
    <query xmlns="urn:xmpp:mam:2" queryid="7f4304f5-265a-4475-bc67-e54be9720eb1">
        <x xmlns="jabber:x:data" type="submit">
            <field var="FORM_TYPE">
                <value>urn:xmpp:mam:2</value>
            </field>
        </x>
    </query>
</iq>
```

But using latest version, the 'to' is ignored.

**Comment by legastero** [comment]
Updated in 12.2.1 to accept either form:

`searchHistory(to, { ... })`
`searchHistory({ to, ... })`

**Comment by legastero** [comment]
And just to be clear, the `to` option is just for specifying where the query gets sent. It doesn't affect any subsequent result filtering (you'd use the `with` option for that, etc).

**Comment by kai670** [comment]
Using prosody's mod_muc_mam the `to` is required to obtain the history of a MUC. I can't completely understand why `with` is not used for that.

**Comment by legastero** [comment]
Several potential answers:

Why require a `to` destination?

Your local user's history archive (used when no `to` attribute is specified) is _not_ going to have the full history of the room. At most, only a copy of whatever you saw while joined to the room, but most (all?) MAM implementations don't store group chats in your personal history. So you need to send the query `to` some other place that would have the full history.

Why send `to` a room, not `to` the service and filtering`with` a room?

Pretty much everything related to MUC operates at the room level, and not the global service. So this continues that pattern. But, it's also a matter of how to deal with archives. If there's one global archive you filter to get per-room results, then how to handle holes created when rooms get destroyed, etc. Cleanest implementation wise to have an archive per room.

**Comment by kai670** [comment]
Thank you for the explanation!
