### ISSUE TITLE
Problem sending messages including an oob payload

### ISSUE THREAD

**Issue by kai670** [legastero/stanza#372]
When I call sendMessage with this data:

```
{
  "to": "bob@domain",
  "type": "chat",
  "marker": {
    "type": "markable"
  },
  "oob": {
    "url": "https://domain/fs/5c7ffff140c359005483bbfe/1763703faf1028dbdd691fd9bc86dea6b4d6b780/bGHxFQeRp",
    "desc": "bGHxFQeRp"
  }
}
```

I see a `message:sent` event being triggered exactly like the one I was expecting:

```
{
  "id": "80f8e800-f380-4798-849e-f833dcc60bf5",
  "originId": "80f8e800-f380-4798-849e-f833dcc60bf5",
  "to": "bob@domain",
  "type": "chat",
  "marker": {
    "type": "markable"
  },
  "oob": {
    "url": "https://domain/fs/5c7ffff140c359005483bbfe/1763703faf1028dbdd691fd9bc86dea6b4d6b780/bGHxFQeRp",
    "desc": "bGHxFQeRp"
  }
}
```

But the stanza sent to the server does not include the oob part:
```
<message xmlns="jabber:client" id="80f8e800-f380-4798-849e-f833dcc60bf5" to="bob@quobis" type="chat">
    <origin-id xmlns="urn:xmpp:sid:0" id="80f8e800-f380-4798-849e-f833dcc60bf5" />
    <markable xmlns="urn:xmpp:chat-markers:0" />
</message>
```

There is a problem translating the oob from js to xml or am I doing something wrong?

**Comment by legastero** [comment]
Ok, several items:

- Update to 12.2.2 to get a fixed JXT mapping for this.
- Use `"links"` as the field instead of `"oob"`.
- Use `"description"` instead of `"desc"`.

Test examples added here: https://github.com/legastero/stanza/tree/master/test/protocol-cases/xep0066
