### ISSUE TITLE
Error when processing a roster message response saying no changes occur since previous version

### ISSUE THREAD

**Issue by kai670** [legastero/stanza#373]
When getRoster() is called and includes in the sent stanza a `ver` value stanza breaks processing the answer with this error:
```
        TypeError: Cannot read property 'items' of undefined
            at webpack:///node_modules/stanza/browser-module.js:9399:1
            at Generator.next (<anonymous>)
            at fulfilled (webpack:///node_modules/tslib/tslib.es6.js:70:42
```

## How to reproduce

1. Request the roster for first time. Stanza sends the next message:
```
<iq xmlns="jabber:client" id="8d3b2396-dd8b-4c38-ba5c-64d797c576dc" type="get"><query xmlns="jabber:iq:roster"/></iq>
```

The server answers with:
```
<iq to='alice@domain/oFdy0kte' id='8d3b2396-dd8b-4c38-ba5c-64d797c576dc' xmlns='jabber:client' type='result'><query xmlns='jabber:iq:roster' ver='1'/></iq>
```
And stanza successfully process it.

2. Request the roster for second time: stanza sends the right request including the previously received value in `ver`:

```
<iq xmlns="jabber:client" id="99e0c8e5-6576-4167-ab13-0dcb173b618f" type="get"><query xmlns="jabber:iq:roster" ver="1"/></iq>
```

And the server answers saying no changes occurred since then:
```
<iq to='alice@quobis/s6T6eIlm' id='99e0c8e5-6576-4167-ab13-0dcb173b618f' xmlns='jabber:client' type='result'/>
```

This message is OK according the the RFC (https://xmpp.org/rfcs/rfc6121.html#roster-versioning-request) but stanza breaks when processing it.

**Comment by legastero** [comment]
Good catch, thanks!

Fixed in 12.2.3
