### ISSUE TITLE
chat event not being emitted when receiving a message of type chat

### ISSUE THREAD

**Issue by kai670** [legastero/stanza#374]
I send a message from Alice and `message:sent` event is emitted with this payload:

```
{
  "id": "0ec1da39-2a2e-4abb-9262-bb3f80d4dbff",
  "originId": "0ec1da39-2a2e-4abb-9262-bb3f80d4dbff",
  "to": "bob@domain",
  "type": "chat",
  "body": "",
  "marker": {
    "type": "markable"
  }
}
```

In the Bob client, I see a `message` event:
```
{
  "from": "alice@domain/FUj6-f-j",
  "id": "0ec1da39-2a2e-4abb-9262-bb3f80d4dbff",
  "lang": "",
  "to": "bob@domain",
  "type": "chat",
  "originId": "0ec1da39-2a2e-4abb-9262-bb3f80d4dbff",
  "marker": {
    "type": "markable"
  },
  "stanzaIds": [
    {
      "by": "bob@domain",
      "id": "2hYRzaVPMmd0wA6S"
    }
  ]
}
```

A `stanza` event:
```
{
  "from": "alice@domain/FUj6-f-j",
  "id": "0ec1da39-2a2e-4abb-9262-bb3f80d4dbff",
  "lang": "",
  "to": "bob@domain",
  "type": "chat",
  "originId": "0ec1da39-2a2e-4abb-9262-bb3f80d4dbff",
  "marker": {
    "type": "markable"
  },
  "stanzaIds": [
    {
      "by": "bob@domain",
      "id": "2hYRzaVPMmd0wA6S"
    }
  ]
}
```

A `message:id:0ec1da39-2a2e-4abb-9262-bb3f80d4dbff` event:
```
{
  "from": "alice@domain/FUj6-f-j",
  "id": "0ec1da39-2a2e-4abb-9262-bb3f80d4dbff",
  "lang": "",
  "to": "bob@domain",
  "type": "chat",
  "originId": "0ec1da39-2a2e-4abb-9262-bb3f80d4dbff",
  "marker": {
    "type": "markable"
  },
  "stanzaIds": [
    {
      "by": "bob@domain",
      "id": "2hYRzaVPMmd0wA6S"
    }
  ]
}

And a `stream:data` event:
```
{
  "from": "alice@domain/FUj6-f-j",
  "id": "0ec1da39-2a2e-4abb-9262-bb3f80d4dbff",
  "lang": "",
  "to": "bob@domain",
  "type": "chat",
  "originId": "0ec1da39-2a2e-4abb-9262-bb3f80d4dbff",
  "marker": {
    "type": "markable"
  },
  "stanzaIds": [
    {
      "by": "bob@domain",
      "id": "2hYRzaVPMmd0wA6S"
    }
  ]
}
```

But I am expecting a `chat` event that is not being triggered :confused: Does this make any sense? Usually the `chat` event is triggered but I can't see a difference why here it is not. If I'm not wrong every message received of type chat should emit a `chat` event isn't?

Just for reference, this is the stanza I'm receiving:

```
<message type='chat' xmlns='jabber:client' from='alice@domain/FUj6-f-j' to='bob@domain' id='0ec1da39-2a2e-4abb-9262-bb3f80d4dbff'><origin-id xmlns='urn:xmpp:sid:0' id='0ec1da39-2a2e-4abb-9262-bb3f80d4dbff'/><body/><markable xmlns='urn:xmpp:chat-markers:0'/><stanza-id xmlns='urn:xmpp:sid:0' by='bob@domain' id='2hYRzaVPMmd0wA6S'/></message>
```

**Comment by legastero** [comment]
The `chat` and `groupchat` events are only emitted if there is a non-empty body.

**Comment by legastero** [comment]
Those events are intended to be shortcuts for rendering out visible messages. In most cases where you need to do anything more than displaying message content, you're better off just listening for the `message` event.

**Comment by kai670** [comment]
oops, my fault. I forgot that! I suppose the difference here from v11 to v12 is that before it was still emitted for a `''` body. But current behaviour makes more sense.
