### ISSUE TITLE
SCRAM-SHA-XXX-PLUS variants are missing

### ISSUE THREAD

**Issue by Neustradamus** [legastero/stanza#375]
PLUS variant is missing, it is a step of https://github.com/legastero/stanza/issues/295.

Linked to:
- https://github.com/scram-xmpp/info/issues/1

**Comment by legastero** [comment]
Still requires adding TCP/TLS support in order to have channel binding info for enabling PLUS.

The PLUS mechanism variants are _already_ supported for negotiating (but follow the recognize-that-PLUS-was-offered-but-can't-enable-binding route).
