### ISSUE TITLE
Question: Using new Client instead of createClient

### ISSUE THREAD

**Issue by mathieuleddet** [legastero/stanza#377]
Hi there,

In the previous versions we were able to use `new Client` and then only load the plugins  needed by calling `client.use(PLUGIN)`.

Is this still "supported"?

I am asking because I observe that if we use `new Client`, any time we call `use(PLUGIN)` it seems that ALL plugins get used / loaded -- which leads to issues as follows.

For instance (pseudo code here) if I do this:
```
let client = new XMPP.Client(...)
client.use(Roster);
client.use(KeepAlive);
```
I realized that all plugins gets loaded twice because I called use to load 2 plugins.
Side effect (I think) is that when I receive a carbon sent message, 'carbon:sent' is emitted twice. This is because `client.on('message' ...)` handler in `messaging.ts` is run twice, once when I call `use(Roster)` and once when I call `use(KeepAlive)`.

Do you follow me?

Thanks,
Mathieu

**Comment by agnauck** [comment]
When you create your Client like this all plugins get loaded:
`const client = XMPP.createClient({});`

When you create your client like this only core plugins get loaded and you can manual additional required plugins:
`const client = new XMPP.Client({});`
