### ISSUE TITLE
v12 not working with IE11

### ISSUE THREAD

**Issue by saint739** [legastero/stanza#379]
After switching from babel to typesript it stopped working with IE11

> commit 4139667e0c20bd8cd85c06d2b9c84c095afa98ec
> Author: Lance Stout <lancestout@gmail.com>
> Date:   Wed Nov 28 11:41:44 2018 -0800
> 
>     Replace babel+eslint with Typescript+TSLint

http://stanza2.4rums.ru/examples/events-demo.html

**Comment by hongyuan1306** [comment]
Same problem. The script fails to load in IE11 at the following position:

```
function apply(fn, ...args) {
    return (...callArgs) => fn(...args,...callArgs);
}
```

And I found out that IE does not support rest arguments syntax.

Maybe the during build `@babel/plugin-transform-parameters` shall be used to transform it into ES5?

**Comment by hongyuan1306** [comment]
I have struggled some time tweaking my project setup and finally stanza 12.3.x is working fine under IE11. For those in the same shoe, I had taken the following steps to make this version IE 11 compatible. My build environment is webpack 4.x.

1. Make sure the `stanza` library and its dependency the `async` library are transformed. Note the distribution file for `async` library ends with suffix `.mjs`. In my webpack config I have the following:
```
      {
        test: /\.m?js$/,
        include: [
          path.resolve(__dirname, 'node_modules/async'),
          path.resolve(__dirname, 'node_modules/stanza')
        ],
        use: {
          loader: 'babel-loader',
          options: {
            presets: [
              [
                '@babel/preset-env',
                {
                  targets: { chrome: '58', ie: '11' }
                }
              ]
            ]
          }
        }
      },
```

2.  The 12.x version of stanza uses lots of ES2015+ features not supported by IE 11, so polyfills are required. The following is required at the top of my entry script:

```
import 'core-js/stable'
import 'regenerator-runtime/runtime'
import 'whatwg-fetch'
import 'unorm'
```

3. The stanza code itself must be patched for `window.crypto` is available under IE 11 under a different name. See #384 for detail.

After the above preparations, I can successfully send and receive messages in IE 11.

**Comment by saint739** [comment]
> My build environment is webpack 4.x.
Hello I am use babel  аnd I can't repeated your way, I tried use @babel/polyfill, but not succesful.
Can you upload your working solution in any plaсe?

**Comment by hongyuan1306** [comment]
Attached is my `package.json` and `webpack` build configuration file. Some other comments that might help:

1. Do not use `@babel/polyfill`, since according to its doc, it has already been deprecated in favor of including `core-js/stable`.

2. When it still does not work, always rely on the IE developer console to find out the exact problem and try to find the working polyfill. Normally just including the polyfills in my previous  post should suffice.

3. Since version 12.4.0 the problem with `window.crypto` has been fixed. So point 3 of my post can be ignored.

[info.zip](https://github.com/legastero/stanza/files/3759649/info.zip)

**Comment by saint739** [comment]
Hongyuan1306, Big thanks!
It works!
Now I will try to transfer this to my project on Vue

**Comment by saint739** [comment]
I can run Stanza on my Vue project.

Big thanks Hongyuan1306 for help and Legastero for ecxellent work.

This a full "HelloWorld" project with Stanza and Vue for IE11
[VueStanzaIE11.zip](https://github.com/legastero/stanza/files/3761924/VueStanzaIE11.zip)
