### ISSUE TITLE
Not resetting SM pendingAck on resume/failed

### ISSUE THREAD

**Issue by mathieuleddet** [legastero/stanza#382]
Hi !

After a failed stream resumption, is there a specific reason why you do not set `this.pendingAck = false`? You reset most variables but not this one.

https://github.com/legastero/stanza/blob/003628ab90203687ea34b0057d0809ad5b9a4f7d/src/StreamManagement.ts#L130-L135

Thanks,
Mathieu

**Comment by legastero** [comment]
Thank you! This should be fixed now in 12.3.3.
