### ISSUE TITLE
Unable to make XMPP connection with Stanza

### ISSUE THREAD

**Issue by ShadowRanger** [legastero/stanza#389]
So I am using Stanza to attempt to make a connection, but I am failing to do so because of how this particular one is set up.

```
const host = "chat.dm.origin.com";
const username = "secret";
const password = "secret";

const client = XMPP.createClient({
	jid: `${username}@${host}`,
	server: host,
	credentials: {
		host: host,
		username: `${username}`,
		password: password,
		realm: host,
		serviceName: host,
		serviceType: "xmpp",
	},
	resource: "origin",
	transports: {
		websocket: `wss://${host}:5222`,
		bosh: false
	}
});
client.enableKeepAlive({ interval: 60 });
client.connect();
```
This is what I was originally using to make the connection, but whenever I use this I get the following error:
`Client network socket disconnected before secure TLS connection was established`

After extensive research I was able to determine that I am not meant to be using that websocket URL. I had this working fine with a different language and XMPP library. The difference is that one somehow made a direct TCP connection to `chat.dm.origin.com/<Some socket IP here>:5222` instead. I just have no idea how I can get this working with Stanza.

**Comment by legastero** [comment]
The current version of Stanza only supports connecting via WebSocket or BOSH. It does not yet support direct TCP/TLS connections.
