### ISSUE TITLE
stanza with ionic

### ISSUE THREAD

**Issue by oliverschulze** [legastero/stanza#393]
Hi, 
I am trying to get stanza to work with ionic (Angular based framework)

I install it with:
npm install stanza@latest

And then I just import it with:
import * as XMPP from 'stanza';

But when compiling I get:

[ng] ERROR in node_modules/@types/readable-stream/index.d.ts(138,18): error TS2304: Cannot find name 'StringDecoder'.
[ng] node_modules/stanza/jingle/Session.d.ts(32,22): error TS2503: Cannot find namespace 'async'.
[ng]

Any ideas or hints?

**Comment by bongartzc** [comment]
Hello,
have you made any progress on this? I am having the same problem.
If I use an older version of stanza (11.x) it compiles

**Comment by toriqo** [comment]
@bongartzc it compiles, but does it work? :)
