### ISSUE TITLE
Redundant session-terminate ?

### ISSUE THREAD

**Issue by arudnev** [legastero/stanza#403]
While trying to upgrade to 12.4.2 from 11.3.2 I've noticed that now out-of-the box reaction to remote `session-terminate` action in `jingle` is to send explicit `session-terminate` back instead of just sending result and silently ending the session.
I'm not sure if it was an intentional change, so just wanted to mention it.
We were hitting some issues with more recent 11.x versions that we did not have time to dig into till now, had to stay on older version, so I'm not sure at what point this change in behavior got introduced.

It's coming to `ICESession.end(...)` with `silent === true` in reaction to remote `session-terminate` action

https://github.com/legastero/stanza/blob/68b9b5b80bb54a61f5ac064a2251fd7532759478/src/jingle/ICESession.ts#L66

but due to `pc.close()` on the line just above it ends up calling `end()` in `onIceStateChange()`

https://github.com/legastero/stanza/blob/68b9b5b80bb54a61f5ac064a2251fd7532759478/src/jingle/ICESession.ts#L407

as reaction to `pc.iceConnectionState` switching to `closed`

https://github.com/legastero/stanza/blob/68b9b5b80bb54a61f5ac064a2251fd7532759478/src/jingle/ICESession.ts#L45

It seems that this reverse `session-terminate` results into error with condition `service-unavailable` coming back from the client that originated first `session-terminate` because it already removed that session.

Also I've noticed that there is no tag v12.4.x in the repo.

P.S. Thanks a lot for the switch to typescript and plenty of other improvements that went into recent releases.

**Comment by legastero** [comment]
This should be fixed now in 12.4.4.

Thanks!

**Comment by arudnev** [comment]
I've upgraded to 12.4.4 and removed previous workaround code, but it seem that something is not quite right, will need to debug to provide more insights.

After quick review of the change I'm wondering if the rest of `JingleSession.end` would be executed after this point:

https://github.com/legastero/stanza/blob/1e7b93f54be9d6d2c753a1a6f49f46690ac0413d/src/jingle/Session.ts#L277

since `JingleSession._ending` is updated as part of the call to `ICESession.end`:

https://github.com/legastero/stanza/blob/1e7b93f54be9d6d2c753a1a6f49f46690ac0413d/src/jingle/ICESession.ts#L68

Just in case, here is the code that I used as a workaround with 12.4.3:

```typescript
ICESession.prototype.end = function iceSessionEnd(reason = 'success', silent = false) {
  if (this.pc.iceConnectionState !== 'closed') {
    this.pc.close();
    Session.prototype.end.call(this, reason, silent);
  }
};

MediaSession.prototype.end = function mediaSessionEnd(reason: JingleReasonCondition | JingleReason = 'success', silent: boolean = false) {
  for (const receiver of this.pc.getReceivers()) {
    this.onRemoveTrack(receiver.track);
  }
  ICESession.prototype.end.call(this, reason, silent);
};
```

**Comment by arudnev** [comment]
Yeah, as I suspected after reviewing the change the main termination logic is not executed in `JingleSession.end` anymore, which causes https://github.com/legastero/stanza/issues/416

**Comment by legastero** [comment]
Reverted that commit for 12.4.5.

Will take another look at how to fix this.
