### ISSUE TITLE
No "jingle:terminated" event on call "terminateMediaSession" method in other side v12.4.4

### ISSUE THREAD

**Issue by zicrox** [legastero/stanza#416]
Hi stanza team,

In the last version (12.4.4) I have an issue on the first tests with audio calls.

When one side closes the call with the "terminateMediaSession" method the other side does not receive the event "jingle:terminated" and also the "stanzaClient.jingle.sessions" is not cleared, so the next call can be a mess with two sessions out there.

The v12.4.3 runs well so I think it may have something to do with this [commit](https://github.com/legastero/stanza/commit/c367c7115d13510dd7faf9ae2863fe03b6d37283)

This project rocks :)

**Comment by legastero** [comment]
Reverted that commit for 12.4.5.

Thanks!
