### ISSUE TITLE
Is there a way for stanza.io to use MAM_1 instead of it's default MAM_2?

### ISSUE THREAD

**Issue by hansifer** [legastero/stanza#418]
Is there a way for stanza.io to use MAM_1 instead of it's default MAM_2?

_Originally posted by @CricketLaChica in https://github.com/legastero/stanza/issues/154#issuecomment-404310182_

**Comment by CricketLaChica** [comment]
We were forced to fork the project.

**Comment by marc0s** [comment]
No.
