### ISSUE TITLE
Can i use stanza with Electron js ?

### ISSUE THREAD

**Issue by devsiodedra** [legastero/stanza#420]
When i am trying to connect then getting below data in client

`"_events": {
    "presence": [
      null,
      null,
      null,
      null
    ],
    "session:started": [
      null,
      null
    ],
    "disconnected": [
      null,
      null,
      null
    ],
    "session:bound": [
      null,
      null
    ],
    "message": [
      null,
      null,
      null,
      null,
      null
    ],
    "pubsub:published": [
      null,
      null
    ]
  },`

so may i know it work with electron or not ?

**Comment by legastero** [comment]
Yeah, it works in electron. But it looks like you've tried to move the client between the node backend and browser frontend. That's not going to work. It needs to live and stay on either side.

**Comment by devsiodedra** [comment]
Thanks, it already working.
