### ISSUE TITLE
Unable to upgrade to Version 12.x

### ISSUE THREAD

**Issue by simologos** [legastero/stanza#421]
Hi,
we are using Stanza (and the previous Stanza.io) library and are very happy with it. Thanks for building this great library!

However we could not find a way to upgrade to version 12.x. We tried all of them, from 12.0.0 beta 0 all the way to 12.5.0. Same result. I'd like to mention that we are no XMPP experts. We are connecting a local XMPP Server which is basically used to just send notification events to clients (via pub sub). This server is not under our control. Just the client.

With Version 11.3.7 of stanza, everything is working fine and we are able to connect to the server and receive events. The session:started event is fired and we are able to send a presence event:
![Stanza_11 3 7](https://user-images.githubusercontent.com/36052147/72516854-a54d4600-3852-11ea-8360-04ecb7a58d5d.png)

However when using one of the 12.x versions, it seems that nothing happens after the SASL login. Compared to V11.3.7, the bind feature is an empty object and the bind never happens.
![Stanza_12 5 0](https://user-images.githubusercontent.com/36052147/72517050-fc531b00-3852-11ea-8be1-d2debbcb5d4c.png)

The source code used for capturing the events is in the screen shots. In this example we are using BOSH to connect. But the same thing applies for web sockets.

Sorry if this is just a configuration problem in our code.
Thanks for any help!

**Comment by hansifer** [comment]
would love to see a response on this. we are seeing the same issue.

**Comment by legastero** [comment]
It looks like the server is not correctly parsing boolean attribute values to treat both "1" and "true" as true.

Stanza in v12 is sending `xmpp:restart="1"` but v11 was sending `xmpp:restart="true"`. Stanza defaults to using the "1" form for boolean values.

I've updated stanza to emit "true" starting in v12.5.1 for these BOSH attributes.
