### ISSUE TITLE
oauth Authentication

### ISSUE THREAD

**Issue by bongartzc** [legastero/stanza#425]
Is it possible to connect to a xmpp server (we are using ejabberd) with an oauth2 Token instead of the jid and password? As far as I can see ejabberd supports this in V19.x.

**Comment by legastero** [comment]
Yep, use the token value as the password. The X-OAUTH2 mechanism will get used if offered.

You'll still need to know the JID, though.

**Comment by bongartzc** [comment]
Thanks.
