### ISSUE TITLE
call stack size exceeded on big stanzas

### ISSUE THREAD

**Issue by agnauck** [legastero/stanza#432]
When receiving vcards with embedded images the parser throws errors and disconnects the stream. This happens when users have some larger embedded images in their vcards.

The following unit test throws the error `RangeError: Maximum call stack size exceeded` on my machine when I fill the binval ~200K of data.

The websocket and bosh connection seem to treat those errors as InvalidXml Stream errors. But this is only a race condition from the call stack exceeded error.

```
it('big stanzas exceed call stack', () => {
    const parser = new JXT.Parser();

    parser.on('error', (msg: string) => {
        console.log("error: " + msg);
    });

    parser.write("<foo>")
    parser.write("<iq xmlns='jabber:client' to='alex@example.com/13590696894572418276106594' from='foo@example.com.app' type='result' id='83b999d8-bfbc-4718-bd19-260e496a359a'><vCard xmlns='vcard-temp'><FN>Mr. Foo</FN><N><FAMILY/><GIVEN/><MIDDLE/><PREFIX/><SUFFIX/></N><NICKNAME/><URL/><ROLE/><EMAIL><USERID/><INTERNET/></EMAIL><PHOTO><TYPE>image/jpeg</TYPE><BINVAL>add many bytes here</BINVAL></PHOTO></vCard></iq>");
    parser.write("</foo>")
})
```

**Comment by legastero** [comment]
Oh, yikes.

Looks to be from this line: https://github.com/legastero/stanza/blob/master/src/jxt/Parser.ts#L633

**Comment by legastero** [comment]
v12.6.3 should fix this.

Thanks!

**Comment by agnauck** [comment]
thank you Lance for fixing this in record time.
I can confirm that is working now fine with bigger vcards which I receive.

Thanks
