### ISSUE TITLE
vcard interfaces (xep0054)

### ISSUE THREAD

**Issue by agnauck** [legastero/stanza#433]
VCardTempEmail:
- home and work boolean property do not work. They need to by in the types array.

VCardTempPhone:
- value property is missing
- types array is missing ('home 'work', 'cell', 'fax', 'voice', 'msg')

Looks like there are some other incomplete types as well. But those are the types I am using right now and came to my attention first.

**Comment by toriqo** [comment]
VCardTempOrg:

- unit property not being sent to the server

**Comment by agnauck** [comment]
ORGUNIT is defined as multiple, can look in the specs what is correct and update my PR to fix this.

**Comment by toriqo** [comment]
only one child allowed:

```
<!-- Organizational name and units property. -->
<!ELEMENT ORG (ORGNAME, ORGUNIT*)>
  <!ELEMENT ORGNAME (#PCDATA)>
  <!ELEMENT ORGUNIT (#PCDATA)>
```

https://xmpp.org/extensions/xep-0054.html

**Comment by agnauck** [comment]
ya, will update my PR later today to fix this as well.

**Comment by agnauck** [comment]
just pushed an update to PR: https://github.com/legastero/stanza/pull/434

**Comment by legastero** [comment]
`<!ELEMENT ORG (ORGNAME, ORGUNIT*)>` shows `ORGUNIT` is allowed 0 or more times inside an `ORG` element, though.

If at most one was allowed it'd be `ORGUNIT?`.

**Comment by agnauck** [comment]
ya, you are right. Will update the PR ASAP when I have some time

**Comment by agnauck** [comment]
pushed an update
@toriqo works fine for me now with this code:

```
let vcard: VCardTemp = {
    fullName: 'Alexander Gnauck',
    records: [
        { type: 'email', preferred: true, types: ['work'], value: 'alex@example.com' },
        { type: 'tel', value: '0123456789', types: ['work'], preferred: true },
        { type: 'nickname', value: 'Alex' },
        { type: 'organization', value: 'My-Org', units: ['Org-A', 'Org-B'] }
    ]
};
```

**Comment by toriqo** [comment]
> `<!ELEMENT ORG (ORGNAME, ORGUNIT*)>` shows `ORGUNIT` is allowed 0 or more times inside an `ORG` element, though.
> 
> If at most one was allowed it'd be `ORGUNIT?`.

I totally missed the *

I'll give it a try, @agnauck

**Comment by toriqo** [comment]
yeah, can't make it work in Ionic. stanzaio requires a higher ts version.
