### ISSUE TITLE
searchHistory returns items from the beginning

### ISSUE THREAD

**Issue by svbutko** [legastero/stanza#436]
I'm using **MongooseIM** with **mod_mam** to have store and receive history of chats and I stumbled upon the fact that I can't get messages from the end of conversation, instead I can receive everything only from beginning and move till the end using the IDs of messages.

Setting `start` and `end` changes nothing, the result is still being taken from the beginning. Checking the configs went without any success too.

Is there any way to receive the history from the end without having no information about IDs and indexes by simply just using the current date?

Thank you.

**Comment by legastero** [comment]
This will require using [paging](https://xmpp.org/extensions/xep-0059.html) using the `before` option:

```typescript
const batch1 = await client.seachHistory(archiveJID, {
  start: 'YYYY-MM-DD',
  end: 'YYYY-MM-DD',
  paging: {
    before: '',  // An empty string indicates starting at the end of the results
    max: 20      // Pick your page size
  }
});
```

And then on subsequent requests:

```typescript
const batch2 = await client.seachHistory(archiveJID, {
  start: 'YYYY-MM-DD',
  end: 'YYYY-MM-DD',
  paging: {
    before: batch1.paging.first,
    max: 20
  }
});
```

Keep in mind, the order of messages inside of a page (e.g. `batch1.results`) will still be chronological, even though you're paging backward.

**Comment by EmlynC** [comment]
Yes, the confusing thing I found (not the fault of the package but rather something from the spec [XEP-0313](https://xmpp.org/extensions/xep-0313.html)) is that you can't use a messages id in `paging.before` as MAM expects a page id; you are required to use a date time to start the search which can lead to boundary issues.

Using `before: ''` adds an empty `<before />` element to the MAM query.

**Comment by svbutko** [comment]
Thank you for the explanation, many of XEPs aren't straightforward as they should be.
