### ISSUE TITLE
Update XEP-0215: External Service Discovery to :2

### ISSUE THREAD

**Issue by wiktor-k** [legastero/stanza#438]
Hi,

I found out that stanza.io is using `urn:xmpp:extdisco:1` namespace for External Service Discovery while it seems other projects such as Prosody's [mod_turncredentials](https://hg.prosody.im/prosody-modules/file/bbfcd786cc78/mod_turncredentials/mod_turncredentials.lua), [ejabberd](https://www.process-one.net/blog/ejabberd-20-04/) and Conversations use [current](https://xmpp.org/extensions/xep-0215.html#usecases) `urn:xmpp:extdisco:2` namespace.

Would it make sense to just switch namespace to `:2` or do you consider it too risky because of compatibility reasons?

Interestingly it seems that the format didn't actually change and `:2` should be backwards compatible with `:1` immediately.

Thank you for your time!

**Comment by legastero** [comment]
I thought I already had, but I guess that was in a branch somewhere.

Yeah, I'll update that soon.

**Comment by legastero** [comment]
I _knew_ I had done this somewhere. Merged now in https://github.com/legastero/stanza/commit/50e8e158e8f32f8636bc2ad9055e39571bbca04f

Published as 12.9.0, and querying for the older `:1` version is still doable using `client.discoverICEServers({ version: '1' })`.

**Comment by wiktor-k** [comment]
This was super-quick! Thank you very much! :)
