### ISSUE TITLE
Receiving a lot of messages with delay (reason SM Storage)

### ISSUE THREAD

**Issue by svbutko** [legastero/stanza#441]
Hi, after sending several messages in the **chat** (type _chat_) with **markers**, I started to receive (after random period of time, it also sometimes happens on reconnection) messages (event _chat_) with _delay_ and _reason_ SM Storage, though these messages are already in the history and an end user has received and even acknowledged them.

It currently leads to the fact that after receiving these messages, the received messages are being added in the history because of the marking ("_received_")

Why does this happen and how this behaviour can be fixed? Does it have something to do with the steam management? (tried to set _allowResumption_ and _sendReceipts_ to **false** with no luck)

Thank you.

**Comment by aybarsyalcin** [comment]
Hi, same issue is occurred. I reconnect server receive all group message all of them.
