### ISSUE TITLE
Setting presence to different values

### ISSUE THREAD

**Issue by kriegster108** [legastero/stanza#442]
Hello, 

I am trying to set my presence to a different value of my choosing such as 'away' or 'do not distrub' . I see nothing in your documentation to do this. Is there a way to set presence to whatever i want? I do not see support for this basic functionality... or i cannot find an example in documentation.

example stanza of what I want to build and send: 

`<presence xmlns="jabber:client" from="jid@messaging.com" to="jid@messaging.com"><show>away</show></presence>`

**Comment by legastero** [comment]
`client.sendPresence({ show: 'away' })`

Valid show values are `chat`, `away`, `xa` (extended away), `dnd` (do not disturb)
