### ISSUE TITLE
JoinRoom Without History Messages

### ISSUE THREAD

**Issue by aybarsyalcin** [legastero/stanza#443]
Hi,
I have a problem when joining existing room. I joined room then receiving all previous sending messages. But I want to only join room without any message or history.
My flow: create room -> invite members -> then sent 20 message on room -> close app -> Again open app -> connect client -> joinroom() -> X (receive all 20 message. But I don't want)
```
client.joinRoom(jid + '@' + 'conference.' + Global.DOMAIN, nickname, {
      status: 'online',
      joinMuc: {
        history: {
          maxchars: '0',
        },
      },
    });
```
I use this versions:
"stanza": "^12.13.0",
"react": "16.9.0",
"react-native": "0.61.5",

Thanks.

**Comment by legastero** [comment]
In Stanza >= 12, you want to use this:

```js
client.joinRoom(jid + '@' + 'conference.' + Global.DOMAIN, nickname, {
      status: 'online',
      muc: {
        history: {
          maxCharacters: 0,
        },
      },
    });
```

**Comment by aybarsyalcin** [comment]
Thanks response. I changed code. But I still received messages. Do you think could be cache problem?

**Comment by aybarsyalcin** [comment]
Thanks again. Sorry my mistake. It is works.
