### ISSUE TITLE
get inbox

### ISSUE THREAD

**Issue by ameer-blue** [legastero/stanza#446]
hi,
i can get xmpp inbox by [@xmpp/client](https://github.com/xmppjs/xmpp.js) package with code in below:

```
const message = xml(
  'iq',
  { type: 'set', id: '1000' },
  xml('query', 'erlang-solutions.com:xmpp:inbox:0'),
);
await xmpp.send(message);
```

but i can’t do this by stanza! can you please help me?

**Comment by phucnguyen1998** [comment]
you can try "stanza.io" :D

**Comment by phucnguyen1998** [comment]
> you can try "stanza.io" :D

https://github.com/phucnguyen1998/ChatMobile

**Comment by ameer-blue** [comment]
> > you can try "stanza.io" :D
> 
> https://github.com/phucnguyen1998/ChatMobile

your project have not inbox and very basic, can you help me to get inbox with stanza?

**Comment by phucnguyen1998** [comment]
import * as XMPP from 'stanza.io';

if you want to send message :
this.client.sendMessage({
            to: 'jid friend',
            body: 'text'
        });

/*
  * Connect ejabberd and receive message
  */
  connectServer() {

    let client = this.client = XMPP.createClient({
      jid: 'your jid',
      password: 'your pass word',
      transport: '',
      wsURL: ' your websocketUrl '
    });

    client.on('session:started', () => {
      client.getRoster((err, result) => {
      });
      client.sendPresence();
    });

    client.on('chat', (msg) => {
      console.log(msg.body) **_// message from anotherUser send you_**
    });

    client.on('raw', (data) => {
    });

    client.on('raw:outgoing', (xml) => {
    });

    client.on('stream:data', (thing) => {
    });

    client.on('connected', () => {
    });

    client.on('disconnected', (xml) => {
    });

    client.on('unavailable', (a) => {
    })

    client.on('available', (a) => {
    })

    client.on('connected', (xml) => {
    })

    client.on('activity', a => {
    })

    client.connect();
  }



My English not good, I hope you understand :D

**Comment by ameer-blue** [comment]
thank but i want to get chats list (inbox)
