### ISSUE TITLE
Not getting pubsub payload 

### ISSUE THREAD

**Issue by Chetan11-dev** [legastero/stanza#450]
Hello Sir Legastero 
I am facing an issue I have documented the issue for you here
https://github.com/Chetan11-dev/stanzajs-ejabberd-example/blob/master/src/xmpp/pub.sub/utils/pub.sub.helpers.ts
please have a look at it

**Comment by legastero** [comment]
Looked like an issue loading the custom plugin on the secondary subscriber clients. PR sent.

**Comment by Chetan11-dev** [comment]
Thank you very much, Lance. I was able to make pubsub example work it.
![Screenshot from 2020-09-09 12-49-21](https://user-images.githubusercontent.com/53407137/92567272-12f32a00-f29b-11ea-92e0-582285a15765.png)
A small request Lance I see you build an amazing library. It could help more people if we could add a full example with it. I have documented the above project well. Do you think we should make add this to example section. It will really help!!!
