### ISSUE TITLE
Update listing on xmpp.org

### ISSUE THREAD

**Issue by Zash** [legastero/stanza#451]
The [entry for stanza](https://github.com/xsf/xmpp.org/blob/0b719d36e09428d343f3e094d04e06895be0eadb/data/libraries.json#L510-L518) in the [listing on xmpp.org](https://xmpp.org/software/libraries.html) hasn't been renewed since the XSF [introduced new procedures](https://xmpp.org/2017/03/new-xmpp-software-listing-rules/) for dealing with the amount of unmaintained projects in the software listings.

See [updating instructions](https://github.com/xsf/xmpp.org/tree/master/data#updating-information).

Thanks.

**Comment by legastero** [comment]
Thanks @Zash! Submitted renewal https://github.com/xsf/xmpp.org/pull/793
