### ISSUE TITLE
TypeError: Cannot redefine property

### ISSUE THREAD

**Issue by bongartzc** [legastero/stanza#455]
I am using stanza Version 11.3.6 with my app and trying migrate it to angular 9. We are using a few plugins with our app.

During runtime the following error is thrown:
` Error: Uncaught (in promise): TypeError: Cannot redefine property: content-type
TypeError: Cannot redefine property: content-type
    at Function.defineProperty (<anonymous>)
    at JXT.add (index.js:93)
    at JXT.extend (index.js:85)
    at stanzaplugin-http-upload.ts:66
    at JXT.withDefinition (index.js:44)
    at JXT.XMPPShortcuts.JXT.withIQ (browser-module.js:5518)
    at push../src/app/services/technical/xmpp/stanzaplugin-http-upload.ts.StanzaPluginHttpUpload.httpUploadPlugin (stanzaplugin-http-upload.ts:65)
    at Client.use (browser-module.js:6852)`

When debugging I have found out that the following is being called twice:

`stanzas.withIq(function (Stanza) {
          stanzas.extend(requestStanza, contentTypeStanza);
          stanzas.extend(requestStanza, filenameStanza);
          stanzas.extend(requestStanza, sizeStanza);
          stanzas.extend(Stanza, requestStanza);
          stanzas.extend(responseSlot, responseSlotGet); //Extend Slot with get tag
          stanzas.extend(responseSlot, responseSlotPut); //Extend Slot with put tag
          stanzas.extend(Stanza, responseSlot);
        });`

Which seems to be causing the problem. Perhaps it is being caused due to a higher typescript version (>3.6) that is being used by angular 9.

Does anyone have an idea of what I could do?

**Comment by TahaJamil37** [comment]
The previos examples of implementing custom stanzas was not working for me..so i implement custom stanza usnig latest documentation..if you need help with that, you can ask me
