### ISSUE TITLE
Question regarding XEPs

### ISSUE THREAD

**Issue by jensengar** [legastero/stanza#456]
Is there a XEP that describes this: https://github.com/legastero/stanza/blob/master/src/protocol/xep0167.ts#L327? I've explored the mentioned xeps at the top of the file and didn't find anything explicit. Thanks!

**Comment by legastero** [comment]
Trying to remember...

That section is what this line refers to: https://github.com/legastero/stanza/blob/master/src/protocol/xep0167.ts#L10

The best that I can hazily recall was that it never made it into a proper XEP, with https://xmpp.org/extensions/xep-0339.html replacing the need for it.

**Comment by jensengar** [comment]
> That section is what this line refers to: https://github.com/legastero/stanza/blob/master/src/protocol/xep0167.ts#L10

Good to know, thanks.

> The best that I can hazily recall was that it never made it into a proper XEP, with https://xmpp.org/extensions/xep-0339.html replacing the need for it.

I saw this in that xep, but was confused because currently the msid doesn't exist on the ssrc line in the sdp. Is that going to change? Or does stanza need to change from the `stream` element and move that info to the `source` element?
