### ISSUE TITLE
how to force PLAIN auth

### ISSUE THREAD

**Issue by ThomasChiroux** [legastero/stanza#459]
**Describe the bug**
Hi!
I'm migrating from a (quite) older version of stanza.io and can not make my environment work anymore.
My xmpp server uses a JWT auth using jid + password PLAIN mechanism with JWT in the password.

Now my server refuses the connexion because stanza changed the auth scheme from PLAIN to X-OAUTH2

**To Reproduce**
Create a client and connect using jid + jwt as password:

**Expected behavior**

log server side:
stanza.io:
```
<auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='PLAIN'>ADYxNjY2MGFjY2Q4Yj...
```

and now stanzajs:
```
<auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='X-OAUTH2'>ADYxNjY2MGFjYj...
```

**Additional context**

client instantiation:

```
const client = XMPP.createClient({
      jid: 'somejid@somedomain',
      credentials: {
        password: xmppToken
      },
      transports: { websocket: 'wss://someserver' }
    })
```

also tried without credentials object and password directly set with jid. I get the same result.

I've tried to guess if I can set a parameter in credentials to force 'PLAIN' auth, but I did not find anything in the doc neither in the code.

I understand that stanza uses X-OAUTH2 because my server propose the feature at the connexion. (by default it proposes PLAIN and X-OAUTH2)
In fact, i've tried to disable the feature server side, and it works: if the server only propose PLAIN, stanza will use plain. I'ts a workaround, but it's not a production-ready configuration as others may still use OAUTH on the same server.

I can not find where stanza determine that my given password is in fact a JWT, and when it uses XAUTH or PLAIN. there is some magic here because i did not use (on purpose) the 'token' parameter in the credentials object.

So is there a way to force PLAIN when sending auth ?

Thanks,
Regards,
Thomas.

**Comment by legastero** [comment]
X-OAUTH2 is considered preferred over PLAIN, so it will be tried first if both are offered. There is no inspection of passwords to try and guess what mechanism they would work with.

`client.sasl.disable('X-OAUTH2')` will do what you need.

**Comment by ThomasChiroux** [comment]
Thanks, your solution is working fine !!
