### ISSUE TITLE
Problem/Help creating a custom plugin for MucSub that extends messages and presence

### ISSUE THREAD

**Issue by Dedaldino3D** [legastero/stanza#460]
I am trying to reproduce the ejabberd mucsub and so far I have created most of the features but I am debating with the messages and presence events, i want to extend messages and presences to work with this events, in XML:

`<message from="coven@muc.shakespeare.example"
         to="hag66@shakespeare.example/pda">
  <event xmlns="http://jabber.org/protocol/pubsub#event">
    <items node="urn:xmpp:mucsub:nodes:messages">
      <item id="18277869892147515942">
        <message from="coven@muc.shakespeare.example/secondwitch"
                 to="hag66@shakespeare.example/pda"
                 type="groupchat"
                 xmlns="jabber:client">
          <archived xmlns="urn:xmpp:mam:tmp"
                    by="muc.shakespeare.example"
                    id="1467896732929849" />
          <stanza-id xmlns="urn:xmpp:sid:0"
                     by="muc.shakespeare.example"
                     id="1467896732929849" />
          <body>Hello from the MUC room !</body>
        </message>
      </item>
    </items>
  </event>
</message>`

`<message from="coven@muc.shakespeare.example"
         to="hag66@shakespeare.example/pda">
  <event xmlns="http://jabber.org/protocol/pubsub#event">
    <items node="urn:xmpp:mucsub:nodes:presences">
      <item id="8170705750417052518">
        <presence xmlns="jabber:client"
                  from="coven@muc.shakespeare.example/secondwitch"
                  type="unavailable"
                  to="hag66@shakespeare.example/pda">
          <x xmlns="http://jabber.org/protocol/muc#user">
            <item affiliation="none"
                  role="none" />
          </x>
        </presence>
      </item>
    </items>
  </event>
</message>`

`<message from="coven@muc.shakespeare.example"
         to="hag66@shakespeare.example/pda">
   <event xmlns="http://jabber.org/protocol/pubsub#event">
     <items node="urn:xmpp:mucsub:nodes:subscribers">
       <item id="17895981155977588737">
         <subscribe xmlns="urn:xmpp:mucsub:0"
                    jid="bob@server.com"
                    nick="bob"/>
       </item>
     </items>
   </event>
</message>`

I tried doing that:
`
  stanzas.define({
    element: "event",
    namespace: NS_PUBSUB_EVENT,
    path: "message.mucsub",
    type: "mucsub_message",
  });

  stanzas.define({
    element: "items",
    namespace: NS_PUBSUB_EVENT,
    fields: {
      id: JXT.childAttribute(null, "item", "id"),
      node: JXT.attribute("node"),
    },
    path: "message.mucsub",
  });

  JXT.addAlias(NS_MAM_TMP, "archived", [
    { path: "message.mucsub.archived", selector: "mucsub_message" },
  ]);
  JXT.addAlias(NS_SID_0, "stanza-id", [
    { path: "message.mucsub.stanzaIds", selector: "mucsub_message" },
  ]);

  // stanzas.define({
  //   aliases: [{path: "message.mucsub", impliedType: true, selector: "mucsub_message"}],
  //   element: "message",
  //   namespace: NS_CLIENT,
  //   fields: {
  //     to: JXT.JIDAttribute('to'),
  //     type: JXT.attribute('type'),
  //     from: JXT.JIDAttribute('from'),
  //     body: JXT.attribute('body'),
  //   }
  // })

  // stanzas.define({
  //   aliases: [{path: "message.mucsub.archived", selector: "mucsub_message"}],
  //   element: "archived",
  //   namespace: NS_MAM_TMP,
  //   fields: {
  //     by: JXT.JIDAttribute('by'),
  //     id: JXT.attribute('id')
  //   }
  // })
`

But my implementation doesnt work, i'm working with stanza 12.

Please, anyone can help me extending this feature.

**Comment by legastero** [comment]
Mucsub combined with stanza has some quirks that make it not follow the typical stanza pubsub pattern. But it is doable.

Here's a copy of the mucsub definitions I used on a consulting project recently:

```typescript
const NS_MUC_SUB = 'urn:xmpp:mucsub:0';
const mucSub: DefinitionOptions[] = [
    {
        element: 'message',
        namespace: NS_CLIENT,
        aliases: [
            {
                path: 'pubsubeventitem.mucsubMessage'
            }
        ]
    },
    {
        element: 'presence',
        namespace: NS_CLIENT,
        aliases: [
            {
                path: 'pubsubeventitem.mucsubPresence'
            }
        ]
    },
    {
        element: 'subscriptions',
        namespace: NS_MUC_SUB,
        path: 'iq.mucsub',
        type: 'subscriptions',
        typeField: 'type'
    },
    {
        element: 'subscribe',
        namespace: NS_MUC_SUB,
        path: 'iq.mucsub',
        type: 'subscribe',
        fields: {
            jid: attribute('jid'),
            nick: attribute('nick'),
            password: attribute('password'),
            events: multipleChildAttribute(null, 'event', 'node')
        }
    },
    {
        element: 'unsubscribe',
        namespace: NS_MUC_SUB,
        path: 'iq.mucsub',
        type: 'unsubscribe'
    },
    {
        aliases: [
            {
                path: 'iq.mucsub.subscriptions',
                multiple: true,
                selector: 'subscriptions'
            }
        ],
        element: 'subscription',
        namespace: NS_MUC_SUB,
        fields: {
            jid: attribute('jid'),
            events: multipleChildAttribute(null, 'event', 'node')
        }
    }
];
```

Received events look like:

```json
{
  "from": "...",
  "lang": "",
  "to": "...",
  "type": "headline",
  "pubsub": {
    "context": "event",
    "eventType": "items",
    "items": {
      "node": "mucsub-test",
      "retracted": [],
      "published": [
        {
          "id": "f9d882dc-92cd-4a73-ac60-fd7f40b0cd9f",
          "mucsubMessage": {
            "lang": "",
            "alternateLanguageBodies": [
              {
                "lang": "",
                "value": "TEST MUCSUB"
              }
            ],
            "body": "TEST MUCSUB"
          }
        }
      ]
    }
  }
}
```

```json
{
  "from": "...",
  "lang": "",
  "to": "...",
  "type": "headline",
  "pubsub": {
    "context": "event",
    "eventType": "items",
    "items": {
      "node": "mucsub-test",
      "retracted": [],
      "published": [
        {
          "id": "1ecaa44f-ab34-4171-8840-c901b0b9eb3c",
          "mucsubPresence": {
            "lang": "",
            "alternateLanguageStatuses": [
              {
                "lang": "",
                "value": "TEST MUCSUB"
              }
            ],
            "priority": 0,
            "status": "TEST MUCSUB"
          }
        }
      ]
    }
  }
}
```

Note that you'd have to look for `mucsubMessage` and `mucsubPresence` in the published data instead of the usual `content` field for other pubsub data. That's the quirk.
