### ISSUE TITLE
client.getRoomMembers() not providing memebers

### ISSUE THREAD

**Issue by ForGuru** [legastero/stanza#465]
**Describe the bug**

Fetching the members of a group is required but its not providing the JIDs of users who have joined the Group.
I came to know that it needs Admin permission to fetch members.

How to fix this issue ?

**To Reproduce**
Just join the group and call the above function with group JID

**Expected behavior**
Provide the list of participants

**Additional context**

**Comment by marc0s** [comment]
This is something that has to do with the group configuration. You can read more about it in https://xmpp.org/extensions/xep-0045.html#disco-roomitems

**Comment by TahaJamil37** [comment]
> This is something that has to do with the group configuration. You can read more about it in https://xmpp.org/extensions/xep-0045.html#disco-roomitems

   i tried it but facing this issue.. can you look at it https://github.com/legastero/stanza/issues/468
