### ISSUE TITLE
Chat Marker Bug

### ISSUE THREAD

**Issue by TahaJamil37** [legastero/stanza#467]
**Describe the bug**
By  default , chatMarkers is set to true . when i recieved the message , it automatically send recieved chat market ..it also send body tag with the recieved chat marker
`<message xmlns="jabber:client" id="a82d17cf-db7b-488f-9be1-8bae86fb9f1a" to="92331......." type="chat"><origin-id xmlns="urn:xmpp:sid:0" id="a82d17cf-db7b-488f-9be1-8bae86fb9f1a"/><body/><received xmlns="urn:xmpp:chat-markers:0" id="b3ca8846-fbc8-421f-8d13-0ddfb142c6a1"/></message>`

**Expected behavior**
This stanza  should be  send insted of the mentioned above in case of recieved chat marker
```
<message
    from='kingrichard@royalty.england.lit/throne'
    id='message-2'
    to='northumberland@shakespeare.lit/westminster'>
  <thread>sleeping</thread>
  <received xmlns='urn:xmpp:chat-markers:0'
               id='message-1'/>
</message>
```

**Comment by marc0s** [comment]
I don't quite understand your message. Are you saying that a `<thread />` element must be there? That a `<body/>` element must not be there?

**Comment by TahaJamil37** [comment]
> I don't quite understand your message. Are you saying that a `<thread />` element must be there? That a `<body/>` element must not be there?

Yes Exactly.. i  dont want body element there ..

**Comment by TahaJamil37** [comment]
client.on('chat', msg => {

      if(msg.body){
      console.log(msg.body  
   }
   });
yes when this event is triggered , it send recieved chat marker with the body tag ...But i dont want body tag there to be send

**Comment by marc0s** [comment]
The `body` element is added here https://github.com/legastero/stanza/blob/master/src/plugins/messaging.ts#L117 I'm not sure why, our initial implementation didn't have it. Maybe @legastero can chime in and tell us something more about it.

**Comment by legastero** [comment]
No memory why it was set that way, removing it.
