### ISSUE TITLE
Stanza Returning Wrong Response

### ISSUE THREAD

**Issue by TahaJamil37** [legastero/stanza#468]
**Describe the bug**
I have implemented the custom plugin to fetch room configurations 
  
 ```
   stanzas.define({
     element: 'query',
     namespace: 'urn:xmpp:muclight:0#info',
     fields: {
         version: JXT.childText(null, 'version'),

        },
         path: 'iq.mystanza',
       
    });
 client.roominformation = async (jid: string)=> {
     
    const resp = await client.sendIQ({
         type:"get",
            to: jid,
            mystanza: {
           version:'1603-798667',
          
            }
            
        });
        console.log(resp)
```

This is the the IQ which is being sent
`<iq xmlns="jabber:client" id="52c6ba3e-9df6-42dc-80d7-8ee72c163741" type="get" to="08d5ab1a-7c2a-4e53-92c9-c9270d1@muclight..com"><query xmlns="urn:xmpp:muclight:0#affiliations"><version>1603-798667-79325</version></query></iq>`

**Expected behavior**
**This is the IQ wich is being returned when i open NEtwork tab in chrome which is correct ** 
`<iq from='08d5ab1a-7c2a-4e53-92c9-c9270d18e7fe@muclight.stagingchat.waafi.com' to='923438555.com/ad142343d1e706aa1603-887102-25571' id='4c06f36d-5744-4937-8497-39d7854702f1' type='result' xmlns='jabber:client'><query xmlns='urn:xmpp:muclight:0#info'><version>1603-798667-79325</version><configuration><roomname>pract group</roomname><subject></subject></configuration><occupants><user affiliation='member'>3087564568@.com</user><user affiliation='owner'>9234385558@i.com</user></occupants></query></iq>`
**But the Console.log(res)
returning me this. i also want occupants and roomname in the response** 
```
{from: "08d5ab1a-7c2a-4e53-92c9-c9270d18e7fe@muclight..com", id: "4c06f36d-5744-4937-8497-39d7854702f1", lang: "", to: "9234385558@.com/ad142343d1e706aa1603-887102-25571", type: "result", …}
from: "08d5ab1a-7c2a-4e53-92c9-c9270d18e7fe@muclight..com"
id: "4c06f36d-5744-4937-8497-39d7854702f1"
lang: ""
mystanza: {version: "1603-798667-79325"}
to: "923438555866@stagingchat.waafi.com/ad142343d1e706aa1603-887102-25571"
type: "result"

```
**Additional context**

**Comment by TahaJamil37** [comment]
@latentflip @fritzy

**Comment by Dedaldino3D** [comment]
You need to create one more stanza to deal with configuration element.

I think you need to do something like that:

**Comment by Dedaldino3D** [comment]
`
stanzas.define({
    aliases: [{path: 'iq.mystanza'}]
    element: 'query',
    namespace: 'urn:xmpp:muclight:0#info',
    fields: {
        version: JXT.childText(null, 'version'),
    },
    type: "mystanza-type",
    typeField: 'type',
});

stanzas.define({
    aliases: [{path: 'iq.mystanza', selector: 'mystanza-type'}]
    element: 'configuration',
    namespace: 'urn:xmpp:muclight:0#info',
    fields: {
        roomname: JXT.childText(null, 'roomname'),
        subject: JXT.childText(null, 'subject'),
    }
})

stanzas.define({
    aliases: [{path: 'iq.mystanza.occupants', multiple: true, selector: 'mystanza-type'}]
    element: 'occupants',
    namespace: 'urn:xmpp:muclight:0#info',
    fields: {
        affiliation: JXT.childAttribute('user', 'affiliation'),
        jid: JXT.childText(null,'user')
    }
})
`
