### ISSUE TITLE
Angular-10 error, Module '"../../../node_modules/stanza"' declares 'Message' locally, but it is not exported

### ISSUE THREAD

**Issue by joshi-anshul** [legastero/stanza#475]
Hello,

**Describe the bug**
When I try to import "Message" from stanza, its showing below error message
`Module '"../../../node_modules/stanza"' declares 'Message' locally, but it is not exported.`

**To Reproduce**
Just try to import.

**Expected behavior**
It should import without error as working in stanza.io.

thanks

**Comment by legastero** [comment]
Stanza mapping definitions aren't top level exports, to allow extending because of how Typescript does interface merging.

They are accessible through the `Stanzas` export instead:

```ts
import { Stanzas } from stanza;
const msg: Stanzas.Message = { };
```

**Comment by joshi-anshul** [comment]
thanks @legastero
