### ISSUE TITLE
Building more complex queries

### ISSUE THREAD

**Issue by julien51** [legastero/stanza#51]
So far, Stanza.io has been a breeze to use! Our main concern at this point is the size of the .js file (400k!), but we can address that later.

One problem that we've had too is how to build more complex stanza. Luckily I searched and found #47 which gives details... but I'm still unable to find how to extand _existing_ elements with custom attributes.

For example, how would you build a stanza like this one, which [we](https://superfeedr.com) use to [list feeds](http://documentation.superfeedr.com/subscribers.html#listing-feeds-with-xmpp):

``` xml
<iq type="get" from="login@superfeedr.com/home" to="firehoser.superfeedr.com" id="subman1">
 <pubsub xmlns="http://jabber.org/protocol/pubsub" xmlns:superfeedr="http://superfeedr.com/xmpp-pubsub-ext">
  <subscriptions jid="login@superfeedr.com" superfeedr:page="3"/>
 </pubsub>
</iq>
```

The tough part being obviously the `superfeedr:page` attribute =), even though I could not see any method in [pubsub.js](https://github.com/otalk/stanza.io/blob/04e19042a8d9925018a3d5ed7f8bcda015f5f397/lib/plugins/pubsub.js) to actually list nodes, even though i believe this is part of XEP60 IIRC.

Thanks!

(also, I understand the appeal of JSON when building these stanzas... but is there a "regular" builder which just builds XML, without a JSON counterpart?)

**Comment by dynamicdirection** [comment]
Is there  a tutorial for MUC (multi user chat)? I am trying to follow the code, when I call "invite" or "inviteDirect" the other clients that connect to my eJabber server don't get invited.
Please help,
Natan
