### ISSUE TITLE
Not Compatible with Openfire 3.8.1

### ISSUE THREAD

**Issue by jstdoit** [legastero/stanza#67]
When I use this lib to connect to a xmpp service powered by Openfire, it always turn out to respond me with a `conflict` stream error. Please help me.

**Comment by timpisti** [comment]
Same problem here with Openfire 3.9.3 - no any info about it.

**Comment by ForNeVeR** [comment]
You guys could help if you'd copied your XML console output (you can see it in the browser's Network tab if you select web socket connection there).
