### ISSUE TITLE
To big library size

### ISSUE THREAD

**Issue by dmonad** [legastero/stanza#75]
The browserified version of stanza.io is 796kb big (also minified). This is a problem when you intend to use stanza in the browser.

**Comment by ErikBean** [comment]
Just a couple of ideas:
You could use a different bundler like [rollup](https://github.com/rollup/rollup) or something else that has tree shaking, to eliminate the modules you aren't using. 
Also, check out the [different styles of instantiating a client](https://github.com/otalk/stanza.io/blob/master/docs/Reference.md#new-clientoptions) with and without plugins. This way you could bundle in the plugins you need and leave out the ones you don't.

**Comment by nelix** [comment]
https://github.com/legastero/stanza.io/issues/97#issuecomment-265080812
