### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by triniwiz** [legastero/stanza#84]
So i decided to try the method u told me after retrieving the login config i'm getting this error 

invalid non-string/buffer chunk

my client config

  var client = XMPP.createClient ({
                        jid: user.jid,
                        transport: user.transport ,
                        wsURL: user.wsURL,
                        useStreamManagement: user.useStreamManagement,
                        credentials:{
                            serverKey:user.credentials.serverKey,
                            clientKey:user.credentials.clientKey
                        },
                        sasl:user.sasl[1] 
                    });

**Comment by legastero** [comment]
Ah, those two values are going to be binary data. You will likely need to store them as base64 yourself and then use `Buffer()` to extract them later:

```js
serverKey: new Buffer(user.credentials.serverKey, 'base64')
```

**Comment by triniwiz** [comment]
Can I access the Buffer() function through the browser ?
