### ISSUE TITLE
Error adding to mobile project

### ISSUE THREAD

**Issue by triniwiz** [legastero/stanza#85]
Stanza.io works great in the brower but when ever i'm trying to add it to my ionic/cordova project i'm getting a compile error it only happens when i include the stanzaz.io files

Unable to add '/home/triniwiz/WebstormProjects/myapp/platforms/android/build/intermediates/assets/armv7/debug/www/lib/node_modules/stanza.io/node_modules/nsp/node_modules/semver/semver.browser.js.gz': file already in archive (try '-u'?)

**Comment by wmfairuz** [comment]
For Cordova, I use the bundle version of stanza (stanza.bundle.js) and it works OK as far as I know.
