### ISSUE TITLE
Determine if a MUC is joinable by client

### ISSUE THREAD

**Issue by warcode** [legastero/stanza#95]
I have both passworded and affiliation based channels.

I am trying to filter a user's channel list based on if they will actually be able to join said channel.

Any easy way of doing this?

**Comment by legastero** [comment]
First, bear in mind that the only 100% reliable way of determining this information is by actually trying to join the rooms (e.g. it's the only way to test that you have the right passwords, there might be deployment-specific policies, etc).

So this is mostly doable, but not entirely easy.


Checking if a room is password protected, or requires membership:
```js
client.getDiscoInfo(theRoomJID, '', function (err, res) {
    var passwordProtected = res.discoInfo.features.indexOf('muc_passwordprotected') >= 0;
    var membershipRequired = res.discoInfo.features.indexOf('muc_membersonly') >= 0;
});
```

Checking membership status:

```js
client.getRoomMembers(theRoomJID, { items: [ { affiliation: 'member' } ] }, function (err, res) {
    var members = res.mucAdmin.items.map(function (item) {
        return item.jid;
    });
    var amMember = members.indexOf(client.jid.bare) >= 0;
});
```

However, you might need to also query for `admin` and `owner` affiliations.

**Comment by warcode** [comment]
Thanks!

From what I can see the prosody server I am using restricts membership information about your peers.     So members can not get any lists, admins can get the list of members and only the owner can get the lists of owners, admins and members.

For my current use case that is fine as I can make the people who are allowed to access the room into owners. I'll have to look into a prosody plugin to allow the behavior I'm looking for.
