### ISSUE TITLE
Downsizing the bundle of stanza.io

### ISSUE THREAD

**Issue by zooldk** [legastero/stanza#97]
Hi Lance,

I really love using stanza.io and I've been using it for many of my apps and projects. But for some of my projects the bundle file is simply too big. Even when obfuscated and compressed its size is around 600-800k (600k without plugins). Is there any way to reduce the size of the minified bundle? I have tried to remove all plugins by removing the client.use(require('./lib/plugins')); in index.html, but it "only" reduced it by 200k.

Any ideas?

**Comment by fippo** [comment]
@legastero i still want you to write a blog post on disc..

**Comment by legastero** [comment]
@zooldk latest version?

**Comment by zooldk** [comment]
Sorry that I forgot about version. I am using 7.0.6.

**Comment by legastero** [comment]
I recommend updating to 7.1.6 if you're still on 7.0.6

Funnily enough, 7.0.7 was the first release that included significant size drops by switching to not using the full `crypto-browserify` module, which has been the main culprit for large bundle sizes.

Here are the sizes that I get with the latest version (with all plugins, etc):

Bundled: 924kb
Minified: 576kb
Min+Gzip: 120kb

**Comment by zooldk** [comment]
Ok thanks @legastero . It is a lot of size drop but actually I need it to be a bit smaller (around 200-300k). It's because it needs to run on TV and STB's which are limited in power and mem (Also some of the browsers suxx). :-)

BTW: How do i set the ping module active? . Is it done by client.enableKeepAlive(); ? Will that auto. pong the server?

**Comment by legastero** [comment]
Ah, ok. Hitting that size target without using gzip is going to require either dropping promise support, or finding some other way to not have to bundle in the bluebird promise lib. 

I've been wanting to do that for a while anyway, so I'll tackle that next. It'll likely mean a major version bump over the weekend.

After that, the next big item would be disabling the Jingle plugin with its WebRTC dependencies.

Yeah, enableKeepAlive will auto send pings (or stream management acks if enabled)

**Comment by zooldk** [comment]
ahh so its the promise lib that takes all the space?. yeah. having a way to only include some modules and chop it up a bit could be really cool!. 

PS: so enableKeepAlive will both enable pings (XEP-0199) and stream management (XEP-0198)?

@legastero if you want maybe a help with some doc? because its really lacking for some of the functions. .e.g how to use plugins and what enableKeepAlive does etc. :-)
 
Thanks for all the help and a great lib. Lance!

**Comment by axelson** [comment]
Yes, we already have our own promise implementation so it would be great not to be adding that additional overhead.

**Comment by nelix** [comment]
I took a look at hacking some bits off with webpack today.
The biggest causes of the size are due to the configuration interface and way plugins are loaded.
In a production build, requiring stanza.io will cause your bundle to gain 419 kB
The easiest thing we can do to get around this is:
Instead of:
``` javascript
var XMPP = require('stanza.io');
var client = XMPP.createClient({jid: 1});
```
We can do: 
``` javascript
var Client = require('stanza.io/lib/client').Client;
var XMPP = new Client({...});
```
This leads to a bundle size of 253kB

I have managed to get it further down to 199kB pre gzip by using ```webpack.IgnorePlugin()``` to block the SASL auth and transports I don't use. But you could get this down internally by making a new createClient that accepts its SASL, Plugin and Transport dependencies from the caller.

@legastero are you interested in PR for this?

**Comment by amanraghubansi** [comment]
Is there any way to directly get bundled file as i  don't want to run commands 1. npm install inside node_modules/stanza.io 2. make
