### ISSUE TITLE
Multi user chat issue

### ISSUE THREAD

**Issue by madhukar0123** [legastero/stanza#99]
Hi,

   I am unable to join a room and create multi user chat room, I used joinRoom() method but still no event is triggering in muc events .please let me know where I am doing wrong . I am using nodejs and ejabberd server

```
var XMPP = require('stanza.io');


var client = XMPP.createClient({
    jid: 'madhu@localhost',
    password: 'iton@123',
    transport: 'bosh',
    boshURL: 'http://localhost/http-bind/'
});

client.enableKeepAlive();

client.on('session:started', function() {

    client.joinRoom("chat@localhost", 'Daemon');
    setInterval(function() {
        client.sendPresence();
        console.log('daemon presence');
    }, 60000);


    console.log("helllo")

    client.on("muc:available", function(pres) {
        console.log("pres");
    });

    client.on("muc:declined", function(pres) {
        console.log("error");
    });

    client.on("muc:join", function(pres) {
        console.log(pres);
    });

    client.on("muc:subject", function(pres) {
        console.log("error");
    });

    client.on("muc:unavailable", function(pres) {
        console.log("error");
    });

    client.on("muc:destroyed", function(pres) {
        console.log("error");
    });


    client.on("muc:error", function(pres) {
        console.log("error");
    });

    client.getRoomConfig("chat@localhost/Daemon", function(e) {
        console.log(e)
    });


});


client.connect();

```

Thank you

**Comment by legastero** [comment]
You can use `client.on('raw:*', console.log.bind(console))` to see all of the raw traffic, just to be sure there's nothing unusual going on.

It looks like you're trying to join `chat@localhost` which typically would not be a MUC unless you have some special config. Was that just a modified example for privacy or did you mean to join something like `chat@conference.localhost`?

**Comment by madhukar0123** [comment]
Thank you @legastero . It is working by giving the correct format "chat@conference.localhost"

**Comment by madhukar0123** [comment]
Hi,

I am unable to use joinRoom() method by clients other than admin. Does only admin got ability to create Room ?

**Comment by shumy** [comment]
I'm using this to join room. It seems OK, but I also what video conference, how can I add a video stream?
With a point-to-point I can use:
```javascript
var session = client.jingle.createMediaSession(jid);
session.addStream(localMedia.localStream);
session.start();
```
But how about a video conference?
